/**
 * Subpath exports available in the `fluentui-react-native` mono-package.
 * Generated from the mono-package's package.json exports field.
 */
export const MONO_PACKAGE_SUBPATHS = new Set([
  'adapters',
  'android-theme',
  'apple-theme',
  'avatar',
  'badge',
  'button',
  'callout',
  'checkbox',
  'chip',
  'composition',
  'contextual-menu',
  'default-theme',
  'divider',
  'drawer',
  'dropdown',
  'experimental-activity-indicator',
  'experimental-appearance-additions',
  'experimental-avatar',
  'experimental-checkbox',
  'experimental-expander',
  'experimental-menu-button',
  'experimental-native-date-picker',
  'experimental-native-font-metrics',
  'experimental-shadow',
  'experimental-shimmer',
  'focus-trap-zone',
  'focus-zone',
  'foundation-composable',
  'foundation-compose',
  'foundation-settings',
  'foundation-tokens',
  'framework',
  'framework-base',
  'icon',
  'input',
  'interactive-hooks',
  'link',
  'menu',
  'menu-button',
  'notification',
  'overflow',
  'persona',
  'persona-coin',
  'popover',
  'pressable',
  'radio-group',
  'separator',
  'spinner',
  'stack',
  'styling-utils',
  'switch',
  'tablist',
  'text',
  'theme',
  'theme-registry',
  'theme-tokens',
  'theme-types',
  'themed-settings',
  'themed-stylesheet',
  'theming-ramp',
  'theming-react-native',
  'theming-utils',
  'tokens',
  'tooltip',
  'use-slot',
  'use-slots',
  'use-styling',
  'use-tokens',
  'vibrancy-view',
  'win32-theme',
]);

/** The mono-package name. */
export const MONO_PACKAGE_NAME = 'fluentui-react-native';

/** The existing barrel package. */
export const BARREL_PACKAGE = '@fluentui/react-native';
