import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import semverCoerce from 'semver/functions/coerce.js';
import { getAllPackageJsonFiles } from 'workspace-tools';

const OUTPUT_FILE = join(import.meta.dirname, 'src/index.js');

interface PackageManifest {
  name: string;
  version: string;
  private?: boolean;
  devOnly?: boolean;
  devDependencies?: Record<string, string>;
}

type PackageEntry = { name: string; version: string; devOnly?: boolean };

const { name: thisPackageName, devDependencies } = JSON.parse(readFileSync('./package.json', 'utf-8')) as PackageManifest;

const packages: Record<string, PackageEntry> = {};
for (const manifestPath of getAllPackageJsonFiles(OUTPUT_FILE)?.sort() ?? []) {
  const { name, version, private: isPrivate, devOnly } = JSON.parse(readFileSync(manifestPath, 'utf-8')) as PackageManifest;
  if (isPrivate || name === thisPackageName || name === '@fluentui-react-native/codemods') {
    continue;
  }

  if (!name) {
    throw new Error(`${manifestPath} is missing 'name'`);
  }
  if (!version) {
    throw new Error(`${manifestPath} is missing 'version'`);
  }

  packages[name] = { name, version, devOnly };
}

const { major, minor } = semverCoerce(devDependencies?.['react-native']) ?? {};

// When updating FURN to a new react-native version, save the profile for
// the current react-native version in index.js to a new file under src named
// "furn-profile-X.Y.js" and add that profile here. For example:
const profiles: Record<string, Record<string, PackageEntry>> = { [`${major}.${minor}`]: packages };
for (const filename of readdirSync('./src')
  .filter((f: string) => f.startsWith('furn-profile-'))
  .sort()
  .reverse()) {
  Object.assign(profiles, (await import(`./src/${filename}`)).default);
}

const source =
  `// This file was generated by '${basename(import.meta.filename)}'\n` +
  `/* eslint-disable */\n` +
  `module.exports = ${JSON.stringify(profiles, undefined, 2).replaceAll('"', "'")};`;

if (readFileSync(OUTPUT_FILE, 'utf-8') !== source + '\n') {
  writeFileSync(OUTPUT_FILE, source + '\n');
} else {
  console.log('✨  Already up to date');
}
