import { AliasColorTokens } from '@fluentui-react-native/theme-types';

export function mapPipelineToTheme(pipelineOutput: any): AliasColorTokens {
  return {
    neutralForeground1: pipelineOutput.neutralForeground1.fillColorRest,
    neutralForeground2: pipelineOutput.neutralForeground2.fillColorRest,
    neutralForeground2Hover: pipelineOutput.neutralForeground2.fillColorHover,
    neutralForeground2Pressed: pipelineOutput.neutralForeground2.fillColorPressed,
    neutralForeground2Selected: pipelineOutput.neutralForeground2Selected.fillColorRest,
    neutralForeground2Brand: pipelineOutput.neutralForeground2Brand.fillColorRest,
    neutralForeground2BrandHover: pipelineOutput.neutralForeground2Brand.fillColorHover,
    neutralForeground2BrandPressed: pipelineOutput.neutralForeground2Brand.fillColorPressed,
    neutralForeground2BrandSelected: pipelineOutput.neutralForeground2BrandSelected.fillColorRest,
    neutralForeground3: pipelineOutput.neutralForeground3.fillColorRest,
    neutralForeground3Hover: pipelineOutput.neutralForeground3.fillColorHover,
    neutralForeground3Pressed: pipelineOutput.neutralForeground3.fillColorPressed,
    neutralForeground3Selected: pipelineOutput.neutralForeground3Selected.fillColorRest,
    neutralForeground3Brand: pipelineOutput.neutralForeground3Brand.fillColorRest,
    neutralForeground3BrandHover: pipelineOutput.neutralForeground3Brand.fillColorHover,
    neutralForeground3BrandPressed: pipelineOutput.neutralForeground3Brand.fillColorPressed,
    neutralForeground3BrandSelected: pipelineOutput.neutralForeground3BrandSelected.fillColorRest,
    neutralForeground4: pipelineOutput.neutralForeground4.fillColorRest,
    neutralForegroundDisabled: pipelineOutput.neutralForeground1.fillColorDisabled,

    brandForegroundLink: pipelineOutput.brandForegroundLink.fillColorRest,
    brandForegroundLinkHover: pipelineOutput.brandForegroundLink.fillColorHover,
    brandForegroundLinkPressed: pipelineOutput.brandForegroundLink.fillColorPressed,
    brandForegroundLinkSelected: pipelineOutput.brandForegroundLinkSelected.fillColorRest,
    compoundBrandForeground1: pipelineOutput.compoundBrandForeground1.fillColorRest,
    compoundBrandForeground1Hover: pipelineOutput.compoundBrandForeground1.fillColorHover,
    compoundBrandForeground1Pressed: pipelineOutput.compoundBrandForeground1.fillColorPressed,
    brandForeground1: pipelineOutput.brandForeground1.fillColorRest,
    brandForeground2: pipelineOutput.brandForeground2.fillColorRest,

    neutralForegroundInverted: pipelineOutput.neutralForegroundInverted.fillColorRest,
    neutralForegroundOnBrand: pipelineOutput.neutralForegroundOnBrand.fillColorRest,
    neutralForegroundInvertedLink: pipelineOutput.neutralForegroundInvertedLink.fillColorRest,
    neutralForegroundInvertedLinkHover: pipelineOutput.neutralForegroundInvertedLink.fillColorHover,
    neutralForegroundInvertedLinkPressed: pipelineOutput.neutralForegroundInvertedLink.fillColorPressed,
    neutralForegroundInvertedLinkSelected: pipelineOutput.neutralForegroundInvertedLinkSelected.fillColorRest,

    neutralBackground1: pipelineOutput.neutralBackground1.fillColorRest,
    neutralBackground1Hover: pipelineOutput.neutralBackground1.fillColorHover,
    neutralBackground1Pressed: pipelineOutput.neutralBackground1.fillColorPressed,
    neutralBackground1Selected: pipelineOutput.neutralBackground1Selected.fillColorRest,
    neutralBackground2: pipelineOutput.neutralBackground2.fillColorRest,
    neutralBackground2Hover: pipelineOutput.neutralBackground2.fillColorHover,
    neutralBackground2Pressed: pipelineOutput.neutralBackground2.fillColorPressed,
    neutralBackground2Selected: pipelineOutput.neutralBackground2Selected.fillColorRest,
    neutralBackground3: pipelineOutput.neutralBackground3.fillColorRest,
    neutralBackground3Hover: pipelineOutput.neutralBackground3.fillColorHover,
    neutralBackground3Pressed: pipelineOutput.neutralBackground3.fillColorPressed,
    neutralBackground3Selected: pipelineOutput.neutralBackground3Selected.fillColorRest,
    neutralBackground4: pipelineOutput.neutralBackground4.fillColorRest,
    neutralBackground4Hover: pipelineOutput.neutralBackground4.fillColorHover,
    neutralBackground4Pressed: pipelineOutput.neutralBackground4.fillColorPressed,
    neutralBackground4Selected: pipelineOutput.neutralBackground4Selected.fillColorRest,
    neutralBackground5: pipelineOutput.neutralBackground5.fillColorRest,
    neutralBackground5Hover: pipelineOutput.neutralBackground5.fillColorHover,
    neutralBackground5Pressed: pipelineOutput.neutralBackground5.fillColorPressed,
    neutralBackground5Selected: pipelineOutput.neutralBackground5Selected.fillColorRest,
    neutralBackground6: pipelineOutput.neutralBackground6.fillColorRest,
    neutralBackgroundInverted: pipelineOutput.neutralBackgroundInverted.fillColorRest,

    subtleBackground: pipelineOutput.subtleBackground.fillColorRest,
    subtleBackgroundHover: pipelineOutput.subtleBackground.fillColorHover,
    subtleBackgroundPressed: pipelineOutput.subtleBackground.fillColorPressed,
    subtleBackgroundSelected: pipelineOutput.subtleBackgroundSelected.fillColorRest,

    transparentBackground: pipelineOutput.transparentBackground.fillColorRest,
    transparentBackgroundHover: pipelineOutput.transparentBackground.fillColorHover,
    transparentBackgroundPressed: pipelineOutput.transparentBackground.fillColorPressed,
    transparentBackgroundSelected: pipelineOutput.transparentBackgroundSelected.fillColorRest,

    neutralBackgroundDisabled: pipelineOutput.neutralBackground1.fillColorDisabled,

    neutralStencil1: pipelineOutput.neutralStencil1.fillColorRest,
    neutralStencil2: pipelineOutput.neutralStencil2.fillColorRest,

    brandBackground: pipelineOutput.brandBackground.fillColorRest,
    brandBackgroundHover: pipelineOutput.brandBackground.fillColorHover,
    brandBackgroundPressed: pipelineOutput.brandBackground.fillColorPressed,
    brandBackgroundSelected: pipelineOutput.brandBackgroundSelected.fillColorRest,
    compoundBrandBackground1: pipelineOutput.compoundBrandBackground1.fillColorRest,
    compoundBrandBackground1Hover: pipelineOutput.compoundBrandBackground1.fillColorHover,
    compoundBrandBackground1Pressed: pipelineOutput.compoundBrandBackground1.fillColorPressed,

    brandBackgroundStatic: pipelineOutput.brandBackgroundStatic.fillColorRest,
    brandBackground2: pipelineOutput.brandBackground2.fillColorRest,

    neutralStrokeAccessible: pipelineOutput.neutralStrokeAccessible.strokeColorRest,
    neutralStrokeAccessibleHover: pipelineOutput.neutralStrokeAccessible.strokeColorHover,
    neutralStrokeAccessiblePressed: pipelineOutput.neutralStrokeAccessible.strokeColorPressed,
    neutralStrokeAccessibleSelected: pipelineOutput.neutralStrokeAccessibleSelected.strokeColorRest,
    neutralStroke1: pipelineOutput.neutralStroke1.strokeColorRest,
    neutralStroke1Hover: pipelineOutput.neutralStroke1.strokeColorHover,
    neutralStroke1Pressed: pipelineOutput.neutralStroke1.strokeColorPressed,
    neutralStroke1Selected: pipelineOutput.neutralStroke1Selected.strokeColorRest,
    neutralStroke2: pipelineOutput.neutralStroke2.strokeColorRest,
    neutralStroke3: pipelineOutput.neutralStroke3.strokeColorRest,
    brandStroke1: pipelineOutput.brandStroke1.strokeColorRest,
    brandStroke2: pipelineOutput.brandStroke2.strokeColorRest,
    compoundBrandStroke1: pipelineOutput.compoundBrandStroke1.strokeColorRest,
    compoundBrandStroke1Hover: pipelineOutput.compoundBrandStroke1.strokeColorHover,
    compoundBrandStroke1Pressed: pipelineOutput.compoundBrandStroke1.strokeColorPressed,
    neutralStrokeDisabled: pipelineOutput.neutralStroke1.strokeColorDisabled,

    transparentStroke: pipelineOutput.transparentStroke.strokeColorRest,
    transparentStrokeInteractive: pipelineOutput.transparentStroke.strokeColorHover,
    transparentStrokeDisabled: pipelineOutput.transparentStroke.strokeColorDisabled,

    strokeFocus1: pipelineOutput.strokeFocus1.strokeColorRest,
    strokeFocus2: pipelineOutput.strokeFocus2.strokeColorRest,
  };
}
