import type { AliasColorTokens, Variants } from '@fluentui-react-native/theme-types';

export function mapPipelineToTheme(pipelineOutput: any): AliasColorTokens {
  return {
    neutralForeground1: pipelineOutput.neutralForeground1.fillColorRest,
    neutralForeground1Hover: pipelineOutput.neutralForeground1.fillColorHover,
    neutralForeground1Pressed: pipelineOutput.neutralForeground1.fillColorPressed,
    neutralForeground1Selected: pipelineOutput.neutralForeground1.fillColorSelected,
    neutralForeground2: pipelineOutput.neutralForeground2.fillColorRest,
    neutralForeground2Hover: pipelineOutput.neutralForeground2.fillColorHover,
    neutralForeground2Pressed: pipelineOutput.neutralForeground2.fillColorPressed,
    neutralForeground2Selected: pipelineOutput.neutralForeground2.fillColorSelected,
    neutralForeground2BrandHover: pipelineOutput.neutralForeground2.fillColorBrandHover,
    neutralForeground2BrandPressed: pipelineOutput.neutralForeground2.fillColorBrandPressed,
    neutralForeground2BrandSelected: pipelineOutput.neutralForeground2.fillColorBrandSelected,
    neutralForeground3: pipelineOutput.neutralForeground3.fillColorRest,
    neutralForeground3Hover: pipelineOutput.neutralForeground3.fillColorHover,
    neutralForeground3Pressed: pipelineOutput.neutralForeground3.fillColorPressed,
    neutralForeground3Selected: pipelineOutput.neutralForeground3.fillColorSelected,
    neutralForeground3BrandHover: pipelineOutput.neutralForeground3.fillColorBrandHover,
    neutralForeground3BrandPressed: pipelineOutput.neutralForeground3.fillColorBrandPressed,
    neutralForeground3BrandSelected: pipelineOutput.neutralForeground3.fillColorBrandSelected,
    neutralForeground4: pipelineOutput.neutralForeground4.fillColorRest,
    neutralForegroundDisabled: pipelineOutput.neutralForegroundDisabled.fillColorRest,

    brandForegroundLink: pipelineOutput.brandForegroundLink.fillColorRest,
    brandForegroundLinkHover: pipelineOutput.brandForegroundLink.fillColorHover,
    brandForegroundLinkPressed: pipelineOutput.brandForegroundLink.fillColorPressed,
    brandForegroundLinkSelected: pipelineOutput.brandForegroundLink.fillColorSelected,
    compoundBrandForeground1: pipelineOutput.compoundBrandForeground1.fillColorRest,
    compoundBrandForeground1Hover: pipelineOutput.compoundBrandForeground1.fillColorHover,
    compoundBrandForeground1Pressed: pipelineOutput.compoundBrandForeground1.fillColorPressed,
    brandForeground1: pipelineOutput.brandForeground1.fillColorRest,
    brandForeground1Disabled: pipelineOutput.brandForeground1.fillColorDisabled,
    brandForeground1Pressed: pipelineOutput.brandForeground1.fillColorPressed,
    brandForeground2: pipelineOutput.brandForeground2.fillColorRest,

    neutralForegroundInverted: pipelineOutput.neutralForegroundInverted.fillColorRest,
    neutralForegroundOnBrand: pipelineOutput.neutralForegroundOnBrand.fillColorRest,
    neutralForegroundOnBrandHover: pipelineOutput.neutralForegroundOnBrand.fillColorHover,
    neutralForegroundOnBrandPressed: pipelineOutput.neutralForegroundOnBrand.fillColorPressed,
    neutralForegroundOnBrandSelected: pipelineOutput.neutralForegroundOnBrand.fillColorSelected,
    neutralForegroundInvertedLink: pipelineOutput.neutralForegroundInvertedLink.fillColorRest,
    neutralForegroundInvertedLinkHover: pipelineOutput.neutralForegroundInvertedLink.fillColorHover,
    neutralForegroundInvertedLinkPressed: pipelineOutput.neutralForegroundInvertedLink.fillColorPressed,
    neutralForegroundInvertedLinkSelected: pipelineOutput.neutralForegroundInvertedLink.fillColorSelected,

    neutralBackground1: pipelineOutput.neutralBackground1.fillColorRest,
    neutralBackground1Hover: pipelineOutput.neutralBackground1.fillColorHover,
    neutralBackground1Pressed: pipelineOutput.neutralBackground1.fillColorPressed,
    neutralBackground1Selected: pipelineOutput.neutralBackground1.fillColorSelected,
    neutralBackground2: pipelineOutput.neutralBackground2.fillColorRest,
    neutralBackground2Hover: pipelineOutput.neutralBackground2.fillColorHover,
    neutralBackground2Pressed: pipelineOutput.neutralBackground2.fillColorPressed,
    neutralBackground2Selected: pipelineOutput.neutralBackground2.fillColorSelected,
    neutralBackground3: pipelineOutput.neutralBackground3.fillColorRest,
    neutralBackground3Hover: pipelineOutput.neutralBackground3.fillColorHover,
    neutralBackground3Pressed: pipelineOutput.neutralBackground3.fillColorPressed,
    neutralBackground3Selected: pipelineOutput.neutralBackground3.fillColorSelected,
    neutralBackground4: pipelineOutput.neutralBackground4.fillColorRest,
    neutralBackground4Hover: pipelineOutput.neutralBackground4.fillColorHover,
    neutralBackground4Pressed: pipelineOutput.neutralBackground4.fillColorPressed,
    neutralBackground4Selected: pipelineOutput.neutralBackground4.fillColorSelected,
    neutralBackground5: pipelineOutput.neutralBackground5.fillColorRest,
    neutralBackground5Hover: pipelineOutput.neutralBackground5.fillColorHover,
    neutralBackground5Pressed: pipelineOutput.neutralBackground5.fillColorPressed,
    neutralBackground5Selected: pipelineOutput.neutralBackground5.fillColorSelected,
    neutralBackground6: pipelineOutput.neutralBackground6.fillColorRest,
    neutralBackgroundInverted: pipelineOutput.neutralBackgroundInverted.fillColorRest,

    subtleBackground: pipelineOutput.subtleBackground.fillColorRest,
    subtleBackgroundHover: pipelineOutput.subtleBackground.fillColorHover,
    subtleBackgroundPressed: pipelineOutput.subtleBackground.fillColorPressed,
    subtleBackgroundSelected: pipelineOutput.subtleBackground.fillColorSelected,

    transparentBackground: pipelineOutput.transparentBackground.fillColorRest,
    transparentBackgroundHover: pipelineOutput.transparentBackground.fillColorHover,
    transparentBackgroundPressed: pipelineOutput.transparentBackground.fillColorPressed,
    transparentBackgroundSelected: pipelineOutput.transparentBackground.fillColorSelected,

    neutralBackgroundDisabled: pipelineOutput.neutralBackgroundDisabled.fillColorRest,

    neutralStencil1: pipelineOutput.neutralStencil1.fillColorRest,
    neutralStencil2: pipelineOutput.neutralStencil2.fillColorRest,

    brandBackground: pipelineOutput.brandBackground.fillColorRest,
    brandBackgroundHover: pipelineOutput.brandBackground.fillColorHover,
    brandBackgroundPressed: pipelineOutput.brandBackground.fillColorPressed,
    brandBackgroundDisabled: pipelineOutput.brandBackground.fillColorDisabled,
    brandBackgroundSelected: pipelineOutput.brandBackground.fillColorSelected,
    compoundBrandBackground1: pipelineOutput.compoundBrandBackground1.fillColorRest,
    compoundBrandBackground1Hover: pipelineOutput.compoundBrandBackground1.fillColorHover,
    compoundBrandBackground1Pressed: pipelineOutput.compoundBrandBackground1.fillColorPressed,

    brandBackgroundStatic: pipelineOutput.brandBackgroundStatic.fillColorRest,
    brandBackground2: pipelineOutput.brandBackground2.fillColorRest,

    neutralStrokeAccessible: pipelineOutput.neutralStrokeAccessible.strokeColorRest,
    neutralStrokeAccessibleHover: pipelineOutput.neutralStrokeAccessible.strokeColorHover,
    neutralStrokeAccessiblePressed: pipelineOutput.neutralStrokeAccessible.strokeColorPressed,
    neutralStrokeAccessibleSelected: pipelineOutput.neutralStrokeAccessible.strokeColorSelected,
    neutralStroke1: pipelineOutput.neutralStroke1.strokeColorRest,
    neutralStroke1Hover: pipelineOutput.neutralStroke1.strokeColorHover,
    neutralStroke1Pressed: pipelineOutput.neutralStroke1.strokeColorPressed,
    neutralStroke1Selected: pipelineOutput.neutralStroke1.strokeColorSelected,
    neutralStroke2: pipelineOutput.neutralStroke2.strokeColorRest,
    neutralStroke3: pipelineOutput.neutralStroke3.strokeColorRest,
    brandStroke1: pipelineOutput.brandStroke1.strokeColorRest,
    brandStroke2: pipelineOutput.brandStroke2.strokeColorRest,
    compoundBrandStroke1: pipelineOutput.compoundBrandStroke1.strokeColorRest,
    compoundBrandStroke1Hover: pipelineOutput.compoundBrandStroke1.strokeColorHover,
    compoundBrandStroke1Pressed: pipelineOutput.compoundBrandStroke1.strokeColorPressed,
    neutralStrokeDisabled: pipelineOutput.neutralStrokeDisabled.strokeColorRest,

    transparentStroke: pipelineOutput.transparentStroke.strokeColorRest,
    transparentStrokeInteractive: pipelineOutput.transparentStroke.strokeColorHover,
    transparentStrokeDisabled: pipelineOutput.transparentStroke.strokeColorDisabled,

    strokeFocus1: pipelineOutput.strokeFocus1.strokeColorRest,
    strokeFocus2: pipelineOutput.strokeFocus2.strokeColorRest,

    dangerBackground1: pipelineOutput.dangerBackground1.fillColorRest,
    dangerBackground2: pipelineOutput.dangerBackground2.fillColorRest,
    dangerBackground3: pipelineOutput.dangerBackground3.fillColorRest,
    dangerForeground1: pipelineOutput.dangerForeground1.fillColorRest,
    dangerForeground2: pipelineOutput.dangerForeground2.fillColorRest,
    dangerForeground3: pipelineOutput.dangerForeground3.fillColorRest,
    dangerForegroundInverted: pipelineOutput.dangerForegroundInverted.fillColorRest,
    dangerBorderActive: pipelineOutput.dangerBorderActive.strokeColorRest,
    dangerBorder1: pipelineOutput.dangerBorder1.strokeColorRest,
    dangerBorder2: pipelineOutput.dangerBorder2.strokeColorRest,

    successBackground1: pipelineOutput.successBackground1.fillColorRest,
    successBackground2: pipelineOutput.successBackground2.fillColorRest,
    successBackground3: pipelineOutput.successBackground3.fillColorRest,
    successForeground1: pipelineOutput.successForeground1.fillColorRest,
    successForeground2: pipelineOutput.successForeground2.fillColorRest,
    successForeground3: pipelineOutput.successForeground3.fillColorRest,
    successForegroundInverted: pipelineOutput.successForegroundInverted.fillColorRest,
    successBorderActive: pipelineOutput.successBorderActive.strokeColorRest,
    successBorder1: pipelineOutput.successBorder1.strokeColorRest,
    successBorder2: pipelineOutput.successBorder2.strokeColorRest,

    warningBackground1: pipelineOutput.warningBackground1.fillColorRest,
    warningBackground2: pipelineOutput.warningBackground2.fillColorRest,
    warningBackground3: pipelineOutput.warningBackground3.fillColorRest,
    warningForeground1: pipelineOutput.warningForeground1.fillColorRest,
    warningForeground2: pipelineOutput.warningForeground2.fillColorRest,
    warningForeground3: pipelineOutput.warningForeground3.fillColorRest,
    warningForegroundInverted: pipelineOutput.warningForegroundInverted.fillColorRest,
    warningBorderActive: pipelineOutput.warningBorderActive.strokeColorRest,
    warningBorder1: pipelineOutput.warningBorder1.strokeColorRest,
    warningBorder2: pipelineOutput.warningBorder2.strokeColorRest,

    severeBackground1: pipelineOutput.severeBackground1.fillColorRest,
    severeBackground2: pipelineOutput.severeBackground2.fillColorRest,
    severeBackground3: pipelineOutput.severeBackground3.fillColorRest,
    severeForeground1: pipelineOutput.severeForeground1.fillColorRest,
    severeForeground2: pipelineOutput.severeForeground2.fillColorRest,
    severeForeground3: pipelineOutput.severeForeground3.fillColorRest,
    severeBorderActive: pipelineOutput.severeBorderActive.strokeColorRest,
    severeBorder1: pipelineOutput.severeBorder1.strokeColorRest,
    severeBorder2: pipelineOutput.severeBorder2.strokeColorRest,

    outofofficeBackground1: pipelineOutput.outofofficeBackground1.fillColorRest,
    outofofficeBackground2: pipelineOutput.outofofficeBackground2.fillColorRest,
    outofofficeBackground3: pipelineOutput.outofofficeBackground3.fillColorRest,
    outofofficeForeground1: pipelineOutput.outofofficeForeground1.fillColorRest,
    outofofficeForeground2: pipelineOutput.outofofficeForeground2.fillColorRest,
    outofofficeForeground3: pipelineOutput.outofofficeForeground3.fillColorRest,
    outofofficeBorderActive: pipelineOutput.outofofficeBorderActive.strokeColorRest,
    outofofficeBorder1: pipelineOutput.outofofficeBorder1.strokeColorRest,
    outofofficeBorder2: pipelineOutput.outofofficeBorder2.strokeColorRest,
  };
}

export function mapFontPipelineToTheme(pipelineOutput: any): Partial<Variants> {
  return {
    caption1: createVariantValue(pipelineOutput.caption1),
    body1: createVariantValue(pipelineOutput.body1),
    body1Strong: createVariantValue(pipelineOutput.body1Strong),
    body2: createVariantValue(pipelineOutput.body2),
    body2Strong: createVariantValue(pipelineOutput.body2Strong),
    subtitle1: createVariantValue(pipelineOutput.subtitle1),
    subtitle1Strong: createVariantValue(pipelineOutput.subtitle1Strong),
    subtitle2: createVariantValue(pipelineOutput.subtitle2),
    subtitle2Strong: createVariantValue(pipelineOutput.subtitle2Strong),
    title1: createVariantValue(pipelineOutput.title1),
    title1Strong: createVariantValue(pipelineOutput.title1Strong),
    largeTitle: createVariantValue(pipelineOutput.largeTitle),
    display: createVariantValue(pipelineOutput.display),
  };
}

function createVariantValue(variant: any) {
  return { face: 'primary', size: variant.fontSize, weight: variant.fontWeight };
}
