import type { ColorValue } from 'react-native';
import {
  colorDarkRedTint30,
  colorDarkRedTint40,
  colorDarkRedShade30,
  colorDarkRedPrimary,
  colorDarkRedTint20,
  colorCranberryPrimary,
  colorCranberryShade30,
  colorCranberryTint40,
  colorCranberryTint30,
  colorCranberryTint20,
  colorOrchidPrimary,
  colorRedTint20,
  colorRedTint30,
  colorRedTint40,
  colorRedShade30,
  colorRedPrimary,
  colorPumpkinTint20,
  colorPumpkinTint30,
  colorPumpkinTint40,
  colorPumpkinShade30,
  colorPumpkinPrimary,
  colorPeachTint20,
  colorPeachTint30,
  colorPeachTint40,
  colorPeachShade30,
  colorPeachPrimary,
  colorMarigoldTint20,
  colorMarigoldTint30,
  colorMarigoldTint40,
  colorMarigoldShade30,
  colorMarigoldPrimary,
  colorGoldTint20,
  colorGoldTint30,
  colorGoldTint40,
  colorGoldShade30,
  colorGoldPrimary,
  colorBrassTint20,
  colorBrassTint30,
  colorBrassTint40,
  colorBrassShade30,
  colorBrassPrimary,
  colorBrownTint20,
  colorBrownTint30,
  colorBrownTint40,
  colorBrownShade30,
  colorBrownPrimary,
  colorSeafoamTint20,
  colorForestTint20,
  colorForestTint30,
  colorForestTint40,
  colorForestShade30,
  colorForestPrimary,
  colorSeafoamTint30,
  colorSeafoamTint40,
  colorSeafoamShade30,
  colorSeafoamPrimary,
  colorDarkGreenTint20,
  colorDarkGreenTint30,
  colorDarkGreenTint40,
  colorDarkGreenShade30,
  colorDarkGreenPrimary,
  colorLightTealTint20,
  colorLightTealTint30,
  colorLightTealTint40,
  colorLightTealShade30,
  colorLightTealPrimary,
  colorTealTint20,
  colorTealTint30,
  colorTealTint40,
  colorTealShade30,
  colorTealPrimary,
  colorSteelTint20,
  colorSteelTint30,
  colorSteelTint40,
  colorSteelShade30,
  colorSteelPrimary,
  colorBlueTint20,
  colorBlueTint30,
  colorBlueTint40,
  colorBlueShade30,
  colorBluePrimary,
  colorRoyalBlueTint20,
  colorRoyalBlueTint30,
  colorRoyalBlueTint40,
  colorRoyalBlueShade30,
  colorRoyalBluePrimary,
  colorCornflowerTint20,
  colorCornflowerTint30,
  colorCornflowerTint40,
  colorCornflowerShade30,
  colorCornflowerPrimary,
  colorNavyTint20,
  colorNavyTint30,
  colorNavyTint40,
  colorNavyShade30,
  colorNavyPrimary,
  colorLavenderTint20,
  colorLavenderTint30,
  colorLavenderTint40,
  colorLavenderShade30,
  colorLavenderPrimary,
  colorPurpleTint20,
  colorPurpleTint30,
  colorPurpleTint40,
  colorPurpleShade30,
  colorPurplePrimary,
  colorGrapeTint20,
  colorGrapeTint30,
  colorGrapeTint40,
  colorGrapeShade30,
  colorLilacTint20,
  colorLilacTint30,
  colorLilacTint40,
  colorLilacShade30,
  colorGrapePrimary,
  colorLilacPrimary,
  colorPinkTint20,
  colorPinkTint30,
  colorPinkTint40,
  colorPinkShade30,
  colorPinkPrimary,
  colorMagentaTint20,
  colorMagentaTint30,
  colorMagentaTint40,
  colorMagentaShade30,
  colorMagentaPrimary,
  colorPlumTint20,
  colorPlumTint30,
  colorPlumTint40,
  colorPlumShade30,
  colorPlumPrimary,
  colorBeigeTint20,
  colorBeigeTint30,
  colorBeigeTint40,
  colorBeigeShade30,
  colorBeigePrimary,
  colorMinkTint20,
  colorMinkTint30,
  colorMinkTint40,
  colorMinkShade30,
  colorMinkPrimary,
  colorPlatinumTint20,
  colorPlatinumTint30,
  colorPlatinumTint40,
  colorPlatinumShade30,
  colorPlatinumPrimary,
  colorAnchorTint20,
  colorAnchorTint30,
  colorAnchorTint40,
  colorAnchorShade30,
  colorAnchorPrimary,
  colorBurgundyTint20,
  colorBurgundyTint30,
  colorBurgundyTint40,
  colorBurgundyShade30,
  colorBurgundyPrimary,
  colorHotPinkTint20,
  colorHotPinkTint30,
  colorHotPinkTint40,
  colorHotPinkShade30,
  colorHotPinkPrimary,
  colorOrchidTint20,
  colorOrchidTint30,
  colorOrchidTint40,
  colorOrchidShade30,
} from '@fluentui-react-native/design/tokens/global';

export type ColorSet = {
  tint30: ColorValue;
  tint40: ColorValue;
  shade30: ColorValue;
  primary: ColorValue;
  tint20: ColorValue;
};

function getColorSet(tint20: ColorValue, tint30: ColorValue, tint40: ColorValue, shade30: ColorValue, primary: ColorValue): ColorSet {
  return {
    tint30,
    tint40,
    shade30,
    primary,
    tint20,
  };
}

export const colorSets = {
  darkRed: getColorSet(colorDarkRedTint20, colorDarkRedTint30, colorDarkRedTint40, colorDarkRedShade30, colorDarkRedPrimary),
  cranberry: getColorSet(colorCranberryTint20, colorCranberryTint30, colorCranberryTint40, colorCranberryShade30, colorCranberryPrimary),
  red: getColorSet(colorRedTint20, colorRedTint30, colorRedTint40, colorRedShade30, colorRedPrimary),
  pumpkin: getColorSet(colorPumpkinTint20, colorPumpkinTint30, colorPumpkinTint40, colorPumpkinShade30, colorPumpkinPrimary),
  peach: getColorSet(colorPeachTint20, colorPeachTint30, colorPeachTint40, colorPeachShade30, colorPeachPrimary),
  marigold: getColorSet(colorMarigoldTint20, colorMarigoldTint30, colorMarigoldTint40, colorMarigoldShade30, colorMarigoldPrimary),
  gold: getColorSet(colorGoldTint20, colorGoldTint30, colorGoldTint40, colorGoldShade30, colorGoldPrimary),
  brass: getColorSet(colorBrassTint20, colorBrassTint30, colorBrassTint40, colorBrassShade30, colorBrassPrimary),
  brown: getColorSet(colorBrownTint20, colorBrownTint30, colorBrownTint40, colorBrownShade30, colorBrownPrimary),
  forest: getColorSet(colorForestTint20, colorForestTint30, colorForestTint40, colorForestShade30, colorForestPrimary),
  seafoam: getColorSet(colorSeafoamTint20, colorSeafoamTint30, colorSeafoamTint40, colorSeafoamShade30, colorSeafoamPrimary),
  darkGreen: getColorSet(colorDarkGreenTint20, colorDarkGreenTint30, colorDarkGreenTint40, colorDarkGreenShade30, colorDarkGreenPrimary),
  lightTeal: getColorSet(colorLightTealTint20, colorLightTealTint30, colorLightTealTint40, colorLightTealShade30, colorLightTealPrimary),
  teal: getColorSet(colorTealTint20, colorTealTint30, colorTealTint40, colorTealShade30, colorTealPrimary),
  steel: getColorSet(colorSteelTint20, colorSteelTint30, colorSteelTint40, colorSteelShade30, colorSteelPrimary),
  blue: getColorSet(colorBlueTint20, colorBlueTint30, colorBlueTint40, colorBlueShade30, colorBluePrimary),
  royalBlue: getColorSet(colorRoyalBlueTint20, colorRoyalBlueTint30, colorRoyalBlueTint40, colorRoyalBlueShade30, colorRoyalBluePrimary),
  cornflower: getColorSet(
    colorCornflowerTint20,
    colorCornflowerTint30,
    colorCornflowerTint40,
    colorCornflowerShade30,
    colorCornflowerPrimary,
  ),
  navy: getColorSet(colorNavyTint20, colorNavyTint30, colorNavyTint40, colorNavyShade30, colorNavyPrimary),
  lavender: getColorSet(colorLavenderTint20, colorLavenderTint30, colorLavenderTint40, colorLavenderShade30, colorLavenderPrimary),
  purple: getColorSet(colorPurpleTint20, colorPurpleTint30, colorPurpleTint40, colorPurpleShade30, colorPurplePrimary),
  grape: getColorSet(colorGrapeTint20, colorGrapeTint30, colorGrapeTint40, colorGrapeShade30, colorGrapePrimary),
  lilac: getColorSet(colorLilacTint20, colorLilacTint30, colorLilacTint40, colorLilacShade30, colorLilacPrimary),
  pink: getColorSet(colorPinkTint20, colorPinkTint30, colorPinkTint40, colorPinkShade30, colorPinkPrimary),
  magenta: getColorSet(colorMagentaTint20, colorMagentaTint30, colorMagentaTint40, colorMagentaShade30, colorMagentaPrimary),
  plum: getColorSet(colorPlumTint20, colorPlumTint30, colorPlumTint40, colorPlumShade30, colorPlumPrimary),
  beige: getColorSet(colorBeigeTint20, colorBeigeTint30, colorBeigeTint40, colorBeigeShade30, colorBeigePrimary),
  mink: getColorSet(colorMinkTint20, colorMinkTint30, colorMinkTint40, colorMinkShade30, colorMinkPrimary),
  platinum: getColorSet(colorPlatinumTint20, colorPlatinumTint30, colorPlatinumTint40, colorPlatinumShade30, colorPlatinumPrimary),
  anchor: getColorSet(colorAnchorTint20, colorAnchorTint30, colorAnchorTint40, colorAnchorShade30, colorAnchorPrimary),
  burgundy: getColorSet(colorBurgundyTint20, colorBurgundyTint30, colorBurgundyTint40, colorBurgundyShade30, colorBurgundyPrimary),
  hotPink: getColorSet(colorHotPinkTint20, colorHotPinkTint30, colorHotPinkTint40, colorHotPinkShade30, colorHotPinkPrimary),
  orchid: getColorSet(colorOrchidTint20, colorOrchidTint30, colorOrchidTint40, colorOrchidShade30, colorOrchidPrimary),
};

export type NamedColorSet = keyof typeof colorSets;

export function getNamedColorSet(colorName: NamedColorSet): ColorSet {
  return colorSets[colorName];
}
