import * as React from 'react';
import { ScreenRect, Text, View } from 'react-native';
import { Button, Callout, Separator } from '@fluentui/react-native';
import { fabricTesterStyles } from '../Common/styles';
import { CALLOUT_TESTPAGE } from './../../Consts';

export const CalloutTest: React.FunctionComponent<{}> = () => {
  const [showStandardCallout, setShowStandardCallout] = React.useState(false);
  const [showCustomizedCallout, setShowCustomizedCallout] = React.useState(false);
  const [isStandardCalloutVisible, setIsStandardCalloutVisible] = React.useState(false);
  const [isCustomizedCalloutVisible, setIsCustomizedCalloutVisible] = React.useState(false);

  const stdBtnRef = React.useRef<View>(null);
  const custBtnRef = React.useRef<View>(null);
  const [anchorRef, setAnchorRef] = React.useState(stdBtnRef);

  const toggleShowStandardCallout = React.useCallback(() => {
    setShowStandardCallout(!showStandardCallout);

    // Unmounting a callout does not invoke onDismiss; onDismiss is only invoked
    // for dismissals generated by the native app.  When toggling to 'show',
    // the isVisible state will be corrected to 'true' by the onShow callback.
    setIsStandardCalloutVisible(false);
  }, [showStandardCallout, setIsStandardCalloutVisible, setShowStandardCallout]);

  const toggleShowCustomizedCallout = React.useCallback(() => {
    setShowCustomizedCallout(!showCustomizedCallout);

    // Unmounting a callout does not invoke onDismiss; onDismiss is only invoked
    // for dismissals generated by the native app.  When toggling to 'show',
    // the isVisible state will be corrected to 'true' by the onShow callback.
    setIsCustomizedCalloutVisible(false);
  }, [showCustomizedCallout, setIsCustomizedCalloutVisible, setShowCustomizedCallout]);

  const toggleCalloutRef = React.useCallback(() => {
    setAnchorRef(anchorRef === stdBtnRef ? custBtnRef : stdBtnRef);
  }, [anchorRef, setAnchorRef]);

  const onShowStandardCallout = React.useCallback(() => {
    setIsStandardCalloutVisible(true);
  }, [setIsStandardCalloutVisible]);

  const onShowCustomizedCallout = React.useCallback(() => {
    setIsCustomizedCalloutVisible(true);
  }, [setIsCustomizedCalloutVisible]);

  const onDismissStandardCallout = React.useCallback(() => {
    setIsStandardCalloutVisible(false);

    // setting the internal state to false will instigate unmounting the
    // zombie Callout control.
    setShowStandardCallout(false);
  }, [setIsStandardCalloutVisible, setShowStandardCallout]);

  const onDismissCustomizedCallout = React.useCallback(() => {
    setIsCustomizedCalloutVisible(false);

    // setting the internal state to false will instigate unmounting the
    // zombie Callout control.
    setShowCustomizedCallout(false);
  }, [setIsCustomizedCalloutVisible, setShowCustomizedCallout]);

  const myRect: ScreenRect = { screenX: 10, screenY: 10, width: 100, height: 100 };
  return (
    <View>
      <Text style={fabricTesterStyles.testSection} testID={CALLOUT_TESTPAGE}>
        Standard Usage
      </Text>
      <Separator />
      <View ref={stdBtnRef} style={{ flexDirection: 'row' }}>
        <Button content="Press for Callout" onClick={toggleShowStandardCallout} />
        <Text>
          <Text>Visibility: </Text>
          {isStandardCalloutVisible ? <Text style={{ color: 'green' }}>Visible</Text> : <Text style={{ color: 'red' }}>Not Visible</Text>}
        </Text>
      </View>

      {showStandardCallout && (
        <Callout
          target={anchorRef}
          onDismiss={onDismissStandardCallout}
          onShow={onShowStandardCallout}
          accessibilityLabel="Standard Callout"
        >
          <View style={{ height: 200, width: 400 }}>
            <Button content="click to change anchor" onClick={toggleCalloutRef} />
          </View>
        </Callout>
      )}

      <Text style={fabricTesterStyles.testSection}>Customized Usage</Text>
      <Separator />

      <View ref={custBtnRef} style={{ flexDirection: 'row' }}>
        <Button content="Press for Callout" onClick={toggleShowCustomizedCallout} />
        <Text>
          <Text>Visibility: </Text>
          {isCustomizedCalloutVisible ? <Text style={{ color: 'green' }}>Visible</Text> : <Text style={{ color: 'red' }}>Not Visible</Text>}
        </Text>
      </View>

      {showCustomizedCallout && (
        <Callout
          anchorRect={myRect}
          onDismiss={onDismissCustomizedCallout}
          onShow={onShowCustomizedCallout}
          accessibilityLabel="Customized Callout"
          accessibilityRole="alert"
          accessibilityOnShowAnnouncement="Be informed that a customized callout has been opened."
        >
          <View style={{ height: 300, width: 500 }}>
            <Text>just some text so it does not take focus and is not empty.</Text>
          </View>
        </Callout>
      )}
    </View>
  );
};
