import * as React from 'react';
import { ScreenRect, Text, View, Switch } from 'react-native';
import { Button, Callout, Separator, IFocusable, OnRestoreFocusEvent } from '@fluentui/react-native';
import { fabricTesterStyles } from '../Common/styles';
import { CALLOUT_TESTPAGE } from './consts';

export const CalloutTest: React.FunctionComponent<{}> = () => {
  const [showStandardCallout, setShowStandardCallout] = React.useState(false);
  const [showCustomizedCallout, setShowCustomizedCallout] = React.useState(false);
  const [isStandardCalloutVisible, setIsStandardCalloutVisible] = React.useState(false);
  const [isCustomizedCalloutVisible, setIsCustomizedCalloutVisible] = React.useState(false);

  const [shouldSetInitialFocus, setShouldSetInitialFocus] = React.useState(true);
  const onInitialFocusChange = React.useCallback((value) => setShouldSetInitialFocus(value), []);

  const [customRestoreFocus, setCustomRestoreFocus] = React.useState(false);
  const onRestoreFocusChange = React.useCallback((value) => setCustomRestoreFocus(value), []);

  const stdBtnRef = React.useRef<View>(null);
  const decoyBtn1Ref = React.useRef<IFocusable>(null);
  const decoyBtn2Ref = React.useRef<IFocusable>(null);
  const custBtnRef = React.useRef<View>(null);
  const [anchorRef, setAnchorRef] = React.useState(stdBtnRef);

  const toggleShowStandardCallout = React.useCallback(() => {
    setShowStandardCallout(!showStandardCallout);

    // Unmounting a callout does not invoke onDismiss; onDismiss is only invoked
    // for dismissals generated by the native app.  When toggling to 'show',
    // the isVisible state will be corrected to 'true' by the onShow callback.
    setIsStandardCalloutVisible(false);
  }, [showStandardCallout, setIsStandardCalloutVisible, setShowStandardCallout]);

  const toggleShowCustomizedCallout = React.useCallback(() => {
    setShowCustomizedCallout(!showCustomizedCallout);

    // Unmounting a callout does not invoke onDismiss; onDismiss is only invoked
    // for dismissals generated by the native app.  When toggling to 'show',
    // the isVisible state will be corrected to 'true' by the onShow callback.
    setIsCustomizedCalloutVisible(false);
  }, [showCustomizedCallout, setIsCustomizedCalloutVisible, setShowCustomizedCallout]);

  const toggleCalloutRef = React.useCallback(() => {
    setAnchorRef(anchorRef === stdBtnRef ? custBtnRef : stdBtnRef);
  }, [anchorRef, setAnchorRef]);

  const onShowStandardCallout = React.useCallback(() => {
    setIsStandardCalloutVisible(true);
  }, [setIsStandardCalloutVisible]);

  const onShowCustomizedCallout = React.useCallback(() => {
    setIsCustomizedCalloutVisible(true);
  }, [setIsCustomizedCalloutVisible]);

  const onDismissStandardCallout = React.useCallback(() => {
    setIsStandardCalloutVisible(false);

    // setting the internal state to false will instigate unmounting the
    // zombie Callout control.
    setShowStandardCallout(false);
  }, [setIsStandardCalloutVisible, setShowStandardCallout]);

  const onDismissCustomizedCallout = React.useCallback(() => {
    setIsCustomizedCalloutVisible(false);

    // setting the internal state to false will instigate unmounting the
    // zombie Callout control.
    setShowCustomizedCallout(false);
  }, [setIsCustomizedCalloutVisible, setShowCustomizedCallout]);

  const onRestoreFocusStandardCallout = React.useCallback(
    (restoreFocusEvent: OnRestoreFocusEvent) => {
      if (restoreFocusEvent.nativeEvent.containsFocus && decoyBtn1Ref && decoyBtn1Ref.current) {
        decoyBtn1Ref.current.focus();
      } else if (!restoreFocusEvent.nativeEvent.containsFocus && decoyBtn2Ref && decoyBtn2Ref.current) {
        decoyBtn2Ref.current.focus();
      }
    },
    [decoyBtn1Ref, decoyBtn2Ref]
  );

  const myRect: ScreenRect = { screenX: 10, screenY: 10, width: 100, height: 100 };
  return (
    <View>
      <Text style={fabricTesterStyles.testSection} testID={CALLOUT_TESTPAGE}>
        Standard Usage
      </Text>
      <Separator />
      <View ref={stdBtnRef} style={{ flexDirection: 'row' }}>
        <View style={{ flexDirection: 'column' }}>
          <View style={{ flexDirection: 'row' }}>
            <Switch value={shouldSetInitialFocus} onValueChange={onInitialFocusChange} />
            <Text>Set Initial Focus</Text>
          </View>

          <View style={{ flexDirection: 'row' }}>
            <Switch value={customRestoreFocus} onValueChange={onRestoreFocusChange} />
            <Text>Customize Restore Focus</Text>
          </View>
        </View>

        <Separator vertical />

        <View style={{ flexDirection: 'column' }}>
          <Button content="Press for Callout" onClick={toggleShowStandardCallout} />
          <Text>
            <Text>Visibility: </Text>
            {isStandardCalloutVisible ? <Text style={{ color: 'green' }}>Visible</Text> : <Text style={{ color: 'red' }}>Not Visible</Text>}
          </Text>
        </View>
      </View>

      <Separator />

      <Button componentRef={decoyBtn1Ref} content="Custom reFocus w/ focus in Callout" />
      <Button componentRef={decoyBtn2Ref} content="Custom reFocus w/o focus in Callout" />

      {showStandardCallout && (
        <Callout
          target={anchorRef}
          onDismiss={onDismissStandardCallout}
          onShow={onShowStandardCallout}
          onRestoreFocus={customRestoreFocus ? onRestoreFocusStandardCallout : undefined}
          accessibilityLabel="Standard Callout"
          setInitialFocus={shouldSetInitialFocus}
        >
          <View style={{ padding: 20, borderWidth: 2, borderColor: 'black' }}>
            <Button content="click to change anchor" onClick={toggleCalloutRef} />
          </View>
        </Callout>
      )}

      <Text style={fabricTesterStyles.testSection}>Customized Usage</Text>
      <Separator />

      <View ref={custBtnRef} style={{ flexDirection: 'row' }}>
        <Button content="Press for Callout" onClick={toggleShowCustomizedCallout} />
        <Text selectable={true}>
          <Text>Visibility: </Text>
          {isCustomizedCalloutVisible ? <Text style={{ color: 'green' }}>Visible</Text> : <Text style={{ color: 'red' }}>Not Visible</Text>}
        </Text>
      </View>

      {showCustomizedCallout && (
        <Callout
          anchorRect={myRect}
          onDismiss={onDismissCustomizedCallout}
          onShow={onShowCustomizedCallout}
          accessibilityLabel="Customized Callout"
          accessibilityRole="alert"
          accessibilityOnShowAnnouncement="Be informed that a customized callout has been opened."
        >
          <View style={{ padding: 20, borderWidth: 2, borderColor: 'black' }}>
            <Text>just some text so it does not take focus and is not empty.</Text>
          </View>
        </Callout>
      )}
    </View>
  );
};
