// `storybook.requires` is generated by the `withStorybook` metro wrapper (or the
// `storybook-generate` script) from the `main.ts` stories glob. It is git-ignored.
import { view } from './storybook.requires';
import AsyncStorage from '@react-native-async-storage/async-storage';

const StorybookUIRoot = view.getStorybookUI({
  enableWebsockets: false,
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
