require_relative '../../../node_modules/react-native-test-app/test_app'

workspace 'FluentTester.xcworkspace'

use_test_app! do |target|
  target.app do
    platform :ios, '14.0'

    # There is a bug where autolinking isn't working, do specify these manually.
    pod 'FRNAvatar', :path => '../../../packages/experimental/Avatar/FRNAvatar.podspec'
    pod 'FRNDatePicker', :path => '../../../packages/experimental/NativeDatePicker/FRNDatePicker.podspec'
    pod 'react-native-menu', :path => '../../../node_modules/@react-native-menu/menu'
  end
end
