compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
