catalog:
  '@types/jasmine': '5.1.13'
  '@wdio/appium-service': '^9.23.0'
  '@wdio/cli': '^9.23.0'
  '@wdio/globals': '^9.23.0'
  '@wdio/jasmine-framework': '^9.23.0'
  '@wdio/json-reporter': '^9.20.0'
  '@wdio/local-runner': '^9.23.0'
  '@wdio/logger': '^9.18.0'
  '@wdio/runner': '^9.23.0'
  '@wdio/spec-reporter': '^9.20.0'
  'appium': '^3.1.2'
  'appium-mac2-driver': '^3.2.13'
  'appium-uiautomator2-driver': '^6.7.8'
  'appium-windows-driver': '^5.1.5'
  'appium-xcuitest-driver': '^10.14.5'
  'expect-webdriverio': '^5.6.1'
  'rimraf': '^6.1.2'
  'webdriverio': '^9.23.0'

dynamicPackageExtensions: ./scripts/dynamic.extensions.mjs

enableScripts: false

globalFolder: .yarn/store

nodeLinker: pnpm

packageExtensions:
  'appium@*':
    dependencies:
      '@colors/colors': '*'
      'appium-mac2-driver': '*'
      'appium-uiautomator2-driver': '*'
      'appium-windows-driver': '*'
      'appium-xcuitest-driver': '*'
  'appium-mac2-driver@*':
    dependencies:
      'appium': '*'
  'appium-uiautomator2-driver@*':
    dependencies:
      'appium': '*'
  'appium-windows-driver@*':
    dependencies:
      'appium': '*'
  'appium-xcuitest-driver@*':
    dependencies:
      'appium': '*'
  'iconv-lite@*':
    dependencies:
      'iconv-lite': '*'
  '@wdio/appium-service@*':
    dependencies:
      'appium': '*'
  'appium-webdriveragent@*':
    dependencies:
      appium-xcode: '*'
  'expect-webdriverio@*':
    dependencies:
      '@wdio/globals': '*'
      '@wdio/logger': '*'
      'webdriverio': '*'
  '@wdio/runner@*':
    dependencies:
      'expect-webdriverio': '*'
  '@wdio/jasmine-framework@*':
    dependencies:
      'expect-webdriverio': '*'
  '@svgr/core@*':
    dependencies:
      '@svgr/plugin-jsx': '*'
      '@svgr/plugin-svgo': '*'
  react-native-svg@*:
    dependencies:
      buffer: '*'

plugins:
  - checksum: 672e525b81762c6162366bd3ffec5e86ab8fac2655ef0267047e86a0f32e79a4bde0f170bc30479663f40aa3f006d91f8dc3289f679dd4dc5ae5a5d12ba3ad0b
    path: .yarn/plugins/@rnx-kit/yarn-plugin-dynamic-extensions.cjs
    spec: 'https://raw.githubusercontent.com/microsoft/rnx-kit/main/incubator/yarn-plugin-dynamic-extensions/index.js'

yarnPath: .yarn/releases/yarn-4.11.0.cjs
