nodeLinker: node-modules
npmRegistryServer: 'https://registry.npmjs.org'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'
yarnPath: .yarn/releases/yarn-3.6.1.cjs
