dynamicPackageExtensions: ./scripts/dynamic.extensions.mjs

enableGlobalCache: false

nodeLinker: pnpm

plugins:
  - checksum: 672e525b81762c6162366bd3ffec5e86ab8fac2655ef0267047e86a0f32e79a4bde0f170bc30479663f40aa3f006d91f8dc3289f679dd4dc5ae5a5d12ba3ad0b
    path: .yarn/plugins/@rnx-kit/yarn-plugin-dynamic-extensions.cjs
    spec: "https://raw.githubusercontent.com/microsoft/rnx-kit/main/incubator/yarn-plugin-dynamic-extensions/index.js"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
