catalog:
  '@babel/core': ^7.20.0
  '@babel/plugin-proposal-private-property-in-object': '^7.21.11'
  '@babel/plugin-transform-react-jsx-source': '^7.22.0'
  '@babel/plugin-transform-typescript': '^7.22.0'
  '@babel/preset-env': '^7.20.0'
  '@babel/preset-react': '^7.20.0'
  '@babel/preset-typescript': '^7.20.0'
  '@babel/runtime': ^7.20.0
  '@babel/plugin-transform-react-jsx': '^7.22.0'
  '@rnx-kit/align-deps': ^3.4.0
  '@rnx-kit/babel-preset-metro-react-native': ^3.0.1
  '@rnx-kit/config': ^0.7.4
  '@rnx-kit/eslint-plugin': ^0.9.5
  '@rnx-kit/jest-preset': ^0.3.1
  '@rnx-kit/lint-lockfile': ^0.1.2
  '@rnx-kit/reporter': ^0.1.0
  '@rnx-kit/tools-packages': ^0.1.1
  '@rnx-kit/tools-typescript': ^0.1.1
  '@rnx-kit/tsconfig': ^2.1.1
  '@types/jasmine': 5.1.13
  '@types/node': ^22.19.7
  '@wdio/appium-service': ^9.23.0
  '@wdio/cli': ^9.23.0
  '@wdio/globals': ^9.23.0
  '@wdio/jasmine-framework': ^9.23.0
  '@wdio/json-reporter': ^9.20.0
  '@wdio/local-runner': ^9.23.0
  '@wdio/logger': ^9.18.0
  '@wdio/runner': ^9.23.0
  '@wdio/spec-reporter': ^9.20.0
  appium: ^3.1.2
  appium-mac2-driver: ^3.2.13
  appium-uiautomator2-driver: ^6.7.8
  appium-windows-driver: ^5.1.5
  appium-xcuitest-driver: ^10.14.5
  cross-env: ^10.1.0
  expect-webdriverio: ^5.6.1
  knip: ^5.81.0
  rimraf: ^6.1.2
  webdriverio: ^9.23.0

catalogs:
  '0.73':
    '@callstack/react-native-visionos': ^0.73.0
    '@react-native-async-storage/async-storage': ^1.22.0
    '@react-native-clipboard/clipboard': ^1.14.0
    '@react-native-community/checkbox': ^0.5.15
    '@react-native-community/cli': ^12.1.1
    '@react-native-community/cli-platform-android': ^12.1.1
    '@react-native-community/cli-platform-ios': ^12.1.1
    '@react-native-community/datetimepicker': ^8.0.0
    '@react-native-community/hooks': ^2.8.0
    '@react-native-community/netinfo': ^11.3.0
    '@react-native-masked-view/masked-view': ^0.3.0
    '@react-native/babel-preset': ^0.73.0
    '@react-native/metro-babel-transformer': ^0.73.0
    '@react-native/metro-config': ^0.73.0
    '@react-navigation/native': ^6.0.8
    '@react-navigation/stack': ^6.3.21
    '@rnx-kit/react-native-lazy-index': ^2.1.7
    '@types/react': ^18.2.0
    '@types/react-test-renderer': ^18.2.0
    jest: ^29.2.1
    metro: ^0.80.0
    metro-config: ^0.80.0
    metro-core: ^0.80.0
    metro-resolver: ^0.80.0
    metro-runtime: ^0.80.0
    react: 18.2.0
    react-dom: ^18.2.0
    react-native: ^0.73.0
    react-native-base64: ^0.2.1
    react-native-floating-action: ^1.22.0
    react-native-fs: ^2.18.0
    react-native-gesture-handler: ^2.14.0
    react-native-macos: ^0.73.0
    react-native-modal: ^13.0.0
    react-native-popover-view: ^5.1.8
    react-native-reanimated: ^3.6.0
    react-native-render-html: ^6.1.0
    react-native-safe-area-context: ^4.8.2
    react-native-screens: ^3.28.0
    react-native-shimmer: ^0.6.0
    react-native-sqlite-storage: ^6.0.1
    react-native-svg: '>=15.0.0 <15.13.0'
    react-native-test-app: ^2.5.34
    react-native-webview: ^13.10.0
    react-native-windows: ^0.73.0
    react-test-renderer: 18.2.0
  '0.74':
    '@callstack/react-native-visionos': ^0.74.0
    '@react-native-async-storage/async-storage': ^2.0.0
    '@react-native-clipboard/clipboard': ^1.14.0
    '@react-native-community/checkbox': ^0.5.15
    '@react-native-community/cli': ^13.6.4
    '@react-native-community/cli-platform-android': ^13.6.4
    '@react-native-community/cli-platform-ios': ^13.6.4
    '@react-native-community/datetimepicker': ^8.0.0
    '@react-native-community/hooks': ^2.8.0
    '@react-native-community/netinfo': ^11.3.3
    '@react-native-masked-view/masked-view': ^0.3.0
    '@react-native/babel-preset': ^0.74.0
    '@react-native/metro-babel-transformer': ^0.74.0
    '@react-native/metro-config': ^0.74.0
    '@react-navigation/native': ^6.0.8
    '@react-navigation/stack': ^6.3.21
    '@rnx-kit/react-native-lazy-index': ^2.1.7
    '@types/react': ^18.2.0
    '@types/react-test-renderer': ^18.2.0
    jest: ^29.2.1
    metro: ^0.80.3
    metro-config: ^0.80.3
    metro-core: ^0.80.3
    metro-resolver: ^0.80.3
    metro-runtime: ^0.80.3
    react: 18.2.0
    react-dom: ^18.2.0
    react-native: ^0.74.0
    react-native-base64: ^0.2.1
    react-native-floating-action: ^1.22.0
    react-native-fs: ^2.18.0
    react-native-gesture-handler: ^2.18.1
    react-native-macos: ^0.74.0
    react-native-modal: ^13.0.0
    react-native-popover-view: ^5.1.8
    react-native-reanimated: ^3.9.0
    react-native-render-html: ^6.1.0
    react-native-safe-area-context: ^4.10.5
    react-native-screens: ^3.31.0
    react-native-shimmer: ^0.6.0
    react-native-sqlite-storage: ^6.0.1
    react-native-svg: '>=15.4.0 <15.13.0'
    react-native-test-app: ^3.9.2
    react-native-webview: ^13.12.2
    react-native-windows: ^0.74.0
    react-test-renderer: 18.2.0
  '0.78':
    '@callstack/react-native-visionos': ^0.78.0
    '@react-native-async-storage/async-storage': ^2.0.0
    '@react-native-clipboard/clipboard': ^1.16.0
    '@react-native-community/checkbox': ^0.5.20
    '@react-native-community/cli': ^15.0.1
    '@react-native-community/cli-platform-android': ^15.0.1
    '@react-native-community/cli-platform-ios': ^15.0.1
    '@react-native-community/datetimepicker': ^8.0.0
    '@react-native-community/hooks': ^100.1.0
    '@react-native-community/netinfo': ^11.3.3
    '@react-native-masked-view/masked-view': ^0.3.0
    '@react-native/babel-preset': ^0.78.0
    '@react-native/metro-babel-transformer': ^0.78.0
    '@react-native/metro-config': ^0.78.0
    '@react-navigation/native': ^7.1.14
    '@react-navigation/stack': ^7.4.2
    '@rnx-kit/react-native-lazy-index': ^2.1.7
    '@types/react': ^19.0.0
    '@types/react-test-renderer': ^19.0.0
    jest: ^29.2.1
    metro: ^0.81.3
    metro-config: ^0.81.3
    metro-core: ^0.81.3
    metro-resolver: ^0.81.3
    metro-runtime: ^0.81.3
    react: 19.0.0
    react-dom: ^19.0.0
    react-native: ^0.78.0
    react-native-base64: ^0.2.1
    react-native-floating-action: ^1.22.0
    react-native-fs: ^2.18.0
    react-native-gesture-handler: ^2.24.0
    react-native-macos: ^0.78.0
    react-native-modal: ^13.0.0
    react-native-popover-view: ^6.0.1
    react-native-reanimated: ^3.17.0
    react-native-render-html: ^6.1.0
    react-native-safe-area-context: ^5.2.0
    react-native-screens: '>=4.5 <4.14.0'
    react-native-shimmer: ^0.6.0
    react-native-sqlite-storage: ^6.0.1
    react-native-svg: ^15.11.2
    react-native-test-app: ^4.3.1
    react-native-webview: ^13.14.1
    react-native-windows: ^0.78.0
    react-test-renderer: 19.0.0
  '0.81':
    '@callstack/react-native-visionos': ^0.81.0
    '@react-native-async-storage/async-storage': ^2.2.0
    '@react-native-clipboard/clipboard': ^1.16.0
    '@react-native-community/checkbox': ^0.5.20
    '@react-native-community/cli': ^20.0.0
    '@react-native-community/cli-platform-android': ^20.0.0
    '@react-native-community/cli-platform-ios': ^20.0.0
    '@react-native-community/datetimepicker': ^8.4.4
    '@react-native-community/hooks': ^100.1.0
    '@react-native-community/netinfo': ^11.3.3
    '@react-native-masked-view/masked-view': ^0.3.0
    '@react-native/babel-preset': ^0.81.0
    '@react-native/metro-babel-transformer': ^0.81.0
    '@react-native/metro-config': ^0.81.0
    '@react-navigation/native': ^7.1.14
    '@react-navigation/stack': ^7.4.2
    '@rnx-kit/react-native-lazy-index': ^2.1.7
    '@types/react': ^19.1.0
    '@types/react-test-renderer': ^19.1.0
    jest: ^29.2.1
    metro: ^0.83.1
    metro-config: ^0.83.1
    metro-core: ^0.83.1
    metro-resolver: ^0.83.1
    metro-runtime: ^0.83.1
    react: 19.1.0
    react-dom: ^19.1.0
    react-native: ^0.81.0
    react-native-base64: ^0.2.1
    react-native-floating-action: ^1.22.0
    react-native-fs: ^2.18.0
    react-native-gesture-handler: ^2.28.0
    react-native-macos: ^0.81.0
    react-native-modal: ^13.0.0
    react-native-popover-view: ^6.0.1
    react-native-reanimated: ^3.19.0
    react-native-render-html: ^6.1.0
    react-native-safe-area-context: ^5.6.0
    react-native-screens: ^4.19.0
    react-native-shimmer: ^0.6.0
    react-native-sqlite-storage: ^6.0.1
    react-native-svg: ^15.12.1
    react-native-test-app: ^4.4.11
    react-native-webview: ^13.14.1
    react-native-windows: ^0.81.0
    react-test-renderer: 19.1.0

dynamicPackageExtensions: ./scripts/dynamic.extensions.mjs
enableScripts: false
globalFolder: .yarn/store
nodeLinker: pnpm
packageExtensions:
  appium@*:
    dependencies:
      '@colors/colors': '*'
      appium-mac2-driver: '*'
      appium-uiautomator2-driver: '*'
      appium-windows-driver: '*'
      appium-xcuitest-driver: '*'
  appium-mac2-driver@*:
    dependencies:
      appium: '*'
  appium-uiautomator2-driver@*:
    dependencies:
      appium: '*'
  appium-windows-driver@*:
    dependencies:
      appium: '*'
  appium-xcuitest-driver@*:
    dependencies:
      appium: '*'
  iconv-lite@*:
    dependencies:
      iconv-lite: '*'
  '@wdio/appium-service@*':
    dependencies:
      appium: '*'
  appium-webdriveragent@*:
    dependencies:
      appium-xcode: '*'
  expect-webdriverio@*:
    dependencies:
      '@wdio/globals': '*'
      '@wdio/logger': '*'
      webdriverio: '*'
  '@wdio/runner@*':
    dependencies:
      expect-webdriverio: '*'
  '@wdio/jasmine-framework@*':
    dependencies:
      expect-webdriverio: '*'
  '@svgr/core@*':
    dependencies:
      '@svgr/plugin-jsx': '*'
      '@svgr/plugin-svgo': '*'
  react-native-svg@*:
    dependencies:
      buffer: '*'
  react-native-svg-transformer@*:
    peerDependencies:
      '@react-native/metro-babel-transformer': '*'

plugins:
  - checksum: >-
      672e525b81762c6162366bd3ffec5e86ab8fac2655ef0267047e86a0f32e79a4bde0f170bc30479663f40aa3f006d91f8dc3289f679dd4dc5ae5a5d12ba3ad0b
    path: .yarn/plugins/@rnx-kit/yarn-plugin-dynamic-extensions.cjs
    spec: >-
      https://raw.githubusercontent.com/microsoft/rnx-kit/main/incubator/yarn-plugin-dynamic-extensions/index.js
yarnPath: .yarn/releases/yarn-4.11.0.cjs
