// `storybook.requires` is generated by the `withStorybook` metro wrapper (or the
// `storybook-generate` script) from the `main.ts` stories glob. It is git-ignored.
import { view } from './storybook.requires';
import { LiteUI } from '@storybook/react-native-ui-lite';

// We run Storybook in lite mode: the heavy default on-device UI (`@storybook/react-native-ui`,
// which needs reanimated/gesture-handler/etc.) is not bundled. `getStorybookUI` would otherwise
// try to render its `FullUI` (which is mocked out and therefore `undefined`, causing an
// "Element type is invalid" crash), so we provide the lightweight `LiteUI` as the UI component.

// Simple in-memory storage so Storybook doesn't warn about a missing `storage` (we intentionally
// avoid @react-native-async-storage/async-storage, which is another native module). The selected
// story just won't persist across full reloads.
const memoryStore: Record<string, string> = {};
const storage = {
  getItem: async (key: string) => (key in memoryStore ? memoryStore[key] : null),
  setItem: async (key: string, value: string) => {
    memoryStore[key] = value;
  },
};

// `enableWebsockets` + `host`/`port` connect the app to the standalone Storybook channel server
// (`yarn storybook-server`, default ws://127.0.0.1:7007). This lets external agents drive the app —
// select stories, read/update control args — and powers the MCP endpoint. If the server isn't
// running the transport just logs a connection error; the app still works standalone.
const StorybookApp = view.getStorybookUI({
  enableWebsockets: true,
  host: '127.0.0.1',
  port: 7007,
  CustomUIComponent: LiteUI,
  storage,
});

export default StorybookApp;
