import {
  cornerRadius120,
  cornerRadius20,
  cornerRadius40,
  cornerRadius60,
  cornerRadius80,
  cornerRadiusCircular,
  fontFamilyBase,
  fontFamilyMonospace,
  fontLineHeight100,
  fontLineHeight200,
  fontLineHeight300,
  fontLineHeight400,
  fontLineHeight500,
  fontLineHeight600,
  fontLineHeight800,
  fontLineHeight900,
  fontLineHeight1000,
  fontSize100,
  fontSize200,
  fontSize300,
  fontSize400,
  fontSize500,
  fontSize600,
  fontSize700,
  fontSize800,
  fontSize900,
  fontSize1000,
  fontWeightBold,
  fontWeightMedium,
  fontWeightRegular,
  fontWeightSemibold,
  size20,
  size40,
  size60,
  size80,
  size100,
  size120,
  size160,
  size200,
  size240,
  size280,
  size320,
  size360,
  size400,
  size480,
  size560,
  size640,
  size800,
  strokeWidth10,
  strokeWidth20,
  strokeWidth30,
  strokeWidth40,
} from './global.generated';
import type { FlexTokens } from './flex.types';

/**
 * Default grouped Flex token values. Semantic colors and shadows use the current
 * Flex defaults; non-color values map to the closest cross-platform global token.
 */
export const defaultFlexTokens: FlexTokens = {
  color: {
    surfaceNeutralFarther: '#ebebeb',
    surfaceNeutralFar: '#f5f5f5',
    surfaceNeutralNear: '#fafafa',
    surfaceNeutralNearer: '#ffffff',
    surfaceNeutralTranslucent: '#ffffff80',
    backgroundNeutralHeavy: '#616161',
    backgroundNeutralLoud: '#616161',
    backgroundNeutralSoft: '#0000001a',
    backgroundNeutralSubtle: '#fafafa',
    backgroundNeutralTransparent: '#00000000',
    backgroundNeutralTranslucent: '#ffffff80',
    backgroundBrandHeavy: '#185abd',
    backgroundBrandLoud: '#185abd',
    backgroundBrandSoft: '#d2e0f4',
    backgroundBrandSubtle: '#d2e0f4',
    backgroundBrandTransparent: '#00000000',
    backgroundDangerLoud: '#d13438',
    backgroundDangerSoft: '#f1bbbc',
    backgroundDangerSubtle: '#fdf6f6',
    backgroundWarningLoud: '#fde300',
    backgroundWarningSoft: '#fef7b2',
    backgroundWarningSubtle: '#fffef5',
    backgroundSuccessLoud: '#107c10',
    backgroundSuccessSoft: '#9fd89f',
    backgroundSuccessSubtle: '#f1faf1',
    strokeNeutralHeavy: '#616161',
    strokeNeutralLoud: '#d1d1d1',
    strokeNeutralSoft: '#d1d1d1',
    strokeNeutralSubtle: '#e0e0e0',
    strokeNeutralTransparent: '#00000000',
    strokeNeutralOnloud: '#ffffff',
    strokeBrandLoud: '#185abd',
    strokeBrandSoft: '#185abd',
    strokeBrandSubtle: '#6794d7',
    strokeBrandOnloud: '#ffffff',
    strokeDangerLoud: '#d13438',
    strokeDangerSoft: '#f1bbbc',
    strokeDangerSubtle: '#f1bbbc',
    strokeDangerOnloud: '#ffffff',
    strokeWarningLoud: '#fde300',
    strokeWarningSoft: '#fef7b2',
    strokeWarningSubtle: '#fef7b2',
    strokeWarningOnloud: '#ffffff',
    strokeSuccessLoud: '#107c10',
    strokeSuccessSoft: '#9fd89f',
    strokeSuccessSubtle: '#9fd89f',
    strokeSuccessOnloud: '#ffffff',
    foregroundNeutralPrimary: '#242424',
    foregroundNeutralSecondary: '#424242',
    foregroundNeutralTertiary: '#616161',
    foregroundNeutralOnloud: '#ffffff',
    foregroundBrandPrimary: '#185abd',
    foregroundBrandOnloud: '#ffffff',
    foregroundDangerPrimary: '#bc2f32',
    foregroundDangerOnloud: '#ffffff',
    foregroundWarningPrimary: '#817400',
    foregroundWarningOnloud: '#ffffff',
    foregroundSuccessPrimary: '#0e700e',
    foregroundSuccessOnloud: '#ffffff',
    fixedWhite: '#ffffff',
    fixedBlack: '#000000',
    expressionAccentHeavy: '#242424',
    expressionAccentLoud: '#707070',
    expressionAccentSoft: '#0000001a',
    expressionAccentSubtle: '#0000000d',
    expressionAchromaticHeavy: '#000000',
    expressionAchromaticSubtle: '#ffffff',
    expressionGrayHeavy: '#474747',
    expressionGrayLoud: '#949494',
    expressionGraySoft: '#e0e0e0',
    expressionGraySubtle: '#f5f5f5',
    expressionNavyHeavy: '#001e89',
    expressionNavyLoud: '#546fd2',
    expressionNavySoft: '#ccd5f3',
    expressionNavySubtle: '#f2f4fc',
    expressionBlueHeavy: '#004377',
    expressionBlueLoud: '#3595de',
    expressionBlueSoft: '#d0e7f8',
    expressionBlueSubtle: '#f3f9fd',
    expressionGreenHeavy: '#0c5e0c',
    expressionGreenLoud: '#54b054',
    expressionGreenSoft: '#c9eac9',
    expressionGreenSubtle: '#f1faf1',
    expressionLimeHeavy: '#405f14',
    expressionLimeLoud: '#689920',
    expressionLimeSoft: '#cfe5af',
    expressionLimeSubtle: '#e5f1d3',
    expressionYellowHeavy: '#4c4400',
    expressionYellowLoud: '#fde300',
    expressionYellowSoft: '#feee66',
    expressionYellowSubtle: '#fef7b2',
    expressionPumpkinHeavy: '#712d09',
    expressionPumpkinLoud: '#df8e64',
    expressionPumpkinSoft: '#f7dfd2',
    expressionPumpkinSubtle: '#fdf7f4',
    expressionRedHeavy: '#751d1f',
    expressionRedLoud: '#dc5e62',
    expressionRedSoft: '#f8dadb',
    expressionRedSubtle: '#fdf6f6',
    expressionPinkHeavy: '#80215d',
    expressionPinkLoud: '#e750b0',
    expressionPinkSoft: '#f7c0e3',
    expressionPinkSubtle: '#fef6fb',
    expressionPurpleHeavy: '#532982',
    expressionPurpleLoud: '#9470bd',
    expressionPurpleSoft: '#e0d3ed',
    expressionPurpleSubtle: '#f7f4fb',
    overlayNeutralTranslucent: '#ffffff80',
    materialBackgroundThick: '#ffffffe6',
    materialBackgroundRegular: '#ffffffcc',
    materialBackgroundThin: '#ffffff80',
    backgroundNeutralDisabled: '#f0f0f0',
    backgroundNeutralHeavyDisabled: '#f0f0f0',
    backgroundNeutralSubtleDisabled: '#f0f0f0',
    strokeNeutralDisabled: '#e0e0e0',
    foregroundNeutralDisabled: '#bdbdbd',
    strokeFocusInner: '#ffffff',
    strokeFocusOuter: '#000000',
    shadow: '#000000',
    hover: {
      surfaceNeutralFarther: '#f5f5f5',
      surfaceNeutralFar: '#ebebeb',
      surfaceNeutralNear: '#f0f0f0',
      surfaceNeutralNearer: '#f5f5f5',
      surfaceNeutralTranslucent: '#ffffff80',
      backgroundNeutralHeavy: '#616161',
      backgroundNeutralLoud: '#616161',
      backgroundNeutralSoft: '#0000001a',
      backgroundNeutralSubtle: '#f0f0f0',
      backgroundNeutralTransparent: '#00000000',
      backgroundNeutralTranslucent: '#ffffff80',
      backgroundBrandHeavy: '#1651aa',
      backgroundBrandLoud: '#1651aa',
      backgroundBrandSoft: '#d2e0f4',
      backgroundBrandSubtle: '#d2e0f4',
      backgroundBrandTransparent: '#00000000',
      backgroundDangerLoud: '#d13438',
      backgroundDangerSoft: '#f1bbbc',
      backgroundDangerSubtle: '#fdf6f6',
      backgroundWarningLoud: '#fde300',
      backgroundWarningSoft: '#fef7b2',
      backgroundWarningSubtle: '#fffef5',
      backgroundSuccessLoud: '#107c10',
      backgroundSuccessSoft: '#9fd89f',
      backgroundSuccessSubtle: '#f1faf1',
      strokeNeutralHeavy: '#575757',
      strokeNeutralLoud: '#c7c7c7',
      strokeNeutralSoft: '#c7c7c7',
      strokeNeutralSubtle: '#e0e0e0',
      strokeNeutralTransparent: '#00000000',
      strokeNeutralOnloud: '#ffffff',
      strokeBrandLoud: '#185abd',
      strokeBrandSoft: '#185abd',
      strokeBrandSubtle: '#6794d7',
      strokeBrandOnloud: '#ffffff',
      strokeDangerLoud: '#d13438',
      strokeDangerSoft: '#f1bbbc',
      strokeDangerSubtle: '#f1bbbc',
      strokeDangerOnloud: '#ffffff',
      strokeWarningLoud: '#fde300',
      strokeWarningSoft: '#fef7b2',
      strokeWarningSubtle: '#fef7b2',
      strokeWarningOnloud: '#ffffff',
      strokeSuccessLoud: '#107c10',
      strokeSuccessSoft: '#9fd89f',
      strokeSuccessSubtle: '#9fd89f',
      strokeSuccessOnloud: '#ffffff',
      foregroundNeutralPrimary: '#242424',
      foregroundNeutralSecondary: '#242424',
      foregroundNeutralTertiary: '#424242',
      foregroundNeutralOnloud: '#ffffff',
      foregroundBrandPrimary: '#185abd',
      foregroundBrandOnloud: '#ffffff',
      foregroundDangerPrimary: '#bc2f32',
      foregroundDangerOnloud: '#ffffff',
      foregroundWarningPrimary: '#817400',
      foregroundWarningOnloud: '#ffffff',
      foregroundSuccessPrimary: '#0e700e',
      foregroundSuccessOnloud: '#ffffff',
    },
    pressed: {
      surfaceNeutralFarther: '#f0f0f0',
      surfaceNeutralFar: '#d6d6d6',
      surfaceNeutralNear: '#dbdbdb',
      surfaceNeutralNearer: '#e0e0e0',
      surfaceNeutralTranslucent: '#ffffff80',
      backgroundNeutralHeavy: '#616161',
      backgroundNeutralLoud: '#616161',
      backgroundNeutralSoft: '#0000001a',
      backgroundNeutralSubtle: '#dbdbdb',
      backgroundNeutralTransparent: '#00000000',
      backgroundNeutralTranslucent: '#ffffff80',
      backgroundBrandHeavy: '#0e336a',
      backgroundBrandLoud: '#0e336a',
      backgroundBrandSoft: '#d2e0f4',
      backgroundBrandSubtle: '#d2e0f4',
      backgroundBrandTransparent: '#00000000',
      backgroundDangerLoud: '#d13438',
      backgroundDangerSoft: '#f1bbbc',
      backgroundDangerSubtle: '#fdf6f6',
      backgroundWarningLoud: '#fde300',
      backgroundWarningSoft: '#fef7b2',
      backgroundWarningSubtle: '#fffef5',
      backgroundSuccessLoud: '#107c10',
      backgroundSuccessSoft: '#9fd89f',
      backgroundSuccessSubtle: '#f1faf1',
      strokeNeutralHeavy: '#4d4d4d',
      strokeNeutralLoud: '#b3b3b3',
      strokeNeutralSoft: '#b3b3b3',
      strokeNeutralSubtle: '#e0e0e0',
      strokeNeutralTransparent: '#00000000',
      strokeNeutralOnloud: '#ffffff',
      strokeBrandLoud: '#185abd',
      strokeBrandSoft: '#185abd',
      strokeBrandSubtle: '#6794d7',
      strokeBrandOnloud: '#ffffff',
      strokeDangerLoud: '#d13438',
      strokeDangerSoft: '#f1bbbc',
      strokeDangerSubtle: '#f1bbbc',
      strokeDangerOnloud: '#ffffff',
      strokeWarningLoud: '#fde300',
      strokeWarningSoft: '#fef7b2',
      strokeWarningSubtle: '#fef7b2',
      strokeWarningOnloud: '#ffffff',
      strokeSuccessLoud: '#107c10',
      strokeSuccessSoft: '#9fd89f',
      strokeSuccessSubtle: '#9fd89f',
      strokeSuccessOnloud: '#ffffff',
      foregroundNeutralPrimary: '#242424',
      foregroundNeutralSecondary: '#242424',
      foregroundNeutralTertiary: '#424242',
      foregroundNeutralOnloud: '#ffffff',
      foregroundBrandPrimary: '#185abd',
      foregroundBrandOnloud: '#ffffff',
      foregroundDangerPrimary: '#bc2f32',
      foregroundDangerOnloud: '#ffffff',
      foregroundWarningPrimary: '#817400',
      foregroundWarningOnloud: '#ffffff',
      foregroundSuccessPrimary: '#0e700e',
      foregroundSuccessOnloud: '#ffffff',
    },
  },
  shadow: {
    lowest: {
      ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
      key: { color: '#00000024', x: 0, y: 1, blur: 2 },
    },
    lower: {
      ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
      key: { color: '#00000024', x: 0, y: 2, blur: 4 },
    },
    low: {
      ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
      key: { color: '#00000024', x: 0, y: 4, blur: 8 },
    },
    high: {
      ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
      key: { color: '#00000024', x: 0, y: 8, blur: 16 },
    },
    higher: {
      ambient: { color: '#00000033', x: 0, y: 0, blur: 8 },
      key: { color: '#0000003d', x: 0, y: 14, blur: 28 },
    },
    highest: {
      ambient: { color: '#00000033', x: 0, y: 0, blur: 8 },
      key: { color: '#0000003d', x: 0, y: 32, blur: 64 },
    },
  },
  fontWeight: {
    functionalRegular: fontWeightRegular,
    functionalMedium: fontWeightMedium,
    functionalSemibold: fontWeightSemibold,
    functionalBold: fontWeightBold,
    contentRegular: fontWeightRegular,
    contentMedium: fontWeightMedium,
    contentSemibold: fontWeightSemibold,
    contentBold: fontWeightBold,
    contentEditorialRegular: fontWeightRegular,
    contentEditorialMedium: fontWeightMedium,
    contentEditorialSemibold: fontWeightSemibold,
    contentEditorialBold: fontWeightBold,
  },
  fontFamily: {
    functional: fontFamilyBase,
    content: fontFamilyBase,
    contentEditorial: fontFamilyBase,
    contentCode: fontFamilyMonospace,
  },
  fontSize: {
    functionalDisplay: fontSize1000,
    functionalPagetitle: fontSize900,
    functionalTitleLarge: fontSize800,
    functionalTitleMedium: fontSize700,
    functionalTitleSmall: fontSize600,
    functionalSubtitle: fontSize500,
    functionalBodyLarge: fontSize400,
    functionalBodyMedium: fontSize300,
    functionalBodySmall: fontSize200,
    functionalCaption: fontSize100,
    contentStatement: fontSize1000,
    contentExpressiveLarge: fontSize900,
    contentExpressiveMedium: fontSize800,
    contentExpressiveSmall: fontSize700,
    contentH1: fontSize800,
    contentH2: fontSize800,
    contentH3: fontSize700,
    contentH4: fontSize600,
    contentH5: fontSize500,
    contentSubheadline: fontSize400,
    contentParagraphLarge: fontSize500,
    contentParagraphMedium: fontSize400,
    contentParagraphSmall: fontSize200,
    contentSubtext: fontSize100,
    contentTable: fontSize400,
    contentCode: fontSize400,
  },
  lineHeight: {
    functionalDisplay: fontLineHeight1000,
    functionalPagetitle: fontLineHeight900,
    functionalTitleLarge: fontLineHeight800,
    functionalTitleMedium: fontLineHeight600,
    functionalTitleSmall: fontLineHeight500,
    functionalSubtitle: fontLineHeight500,
    functionalBodyLarge: fontLineHeight400,
    functionalBodyMedium: fontLineHeight300,
    functionalBodySmall: fontLineHeight200,
    functionalCaption: fontLineHeight100,
    contentStatement: fontLineHeight900,
    contentExpressiveLarge: fontLineHeight900,
    contentExpressiveMedium: fontLineHeight800,
    contentExpressiveSmall: fontLineHeight600,
    contentH1: fontLineHeight800,
    contentH2: fontLineHeight800,
    contentH3: fontLineHeight600,
    contentH4: fontLineHeight500,
    contentH5: fontLineHeight400,
    contentSubheadline: fontLineHeight400,
    contentParagraphLarge: fontLineHeight600,
    contentParagraphMedium: fontLineHeight500,
    contentParagraphSmall: fontLineHeight300,
    contentSubtext: fontLineHeight100,
    contentTable: fontLineHeight400,
    contentCode: fontLineHeight400,
  },
  borderRadius: {
    base100: cornerRadius20,
    base200: cornerRadius40,
    base300: cornerRadius40,
    base400: cornerRadius60,
    base600: cornerRadius80,
    base700: cornerRadius120,
    circular: cornerRadiusCircular,
  },
  spacing: {
    componentBase50: size20,
    componentBase100: size40,
    componentBase150: size60,
    componentBase200: size80,
    componentBase250: size100,
    componentBase300: size120,
    componentBase400: size160,
    componentBase500: size200,
    componentBase600: size240,
    componentBase700: size280,
    layoutBase100: size80,
    layoutBase200: size160,
    layoutBase300: size240,
    layoutBase400: size320,
    layoutBase450: size360,
    layoutBase500: size400,
    layoutBase600: size480,
    layoutBase700: size560,
    layoutBase800: size640,
    layoutBase1000: size800,
    layoutBase1200: size800,
  },
  strokeWidth: {
    thin: strokeWidth10,
    thick: strokeWidth20,
    thicker: strokeWidth30,
    thickest: strokeWidth40,
  },
};
