import type { FlexTokens } from './flex.types';

/**
 * Use the mapping of semantic color tokens to their alias names to generate a temporary default set of color tokens.
 * These map to values from the @fluentui-react-native/design-tokens-win32 package under the colorful path.
 */
export const defaultSemanticColors: FlexTokens = {
  colorSurfaceNeutralFarther: '#ebebeb',
  colorSurfaceNeutralFar: '#f5f5f5',
  colorSurfaceNeutralNear: '#fafafa',
  colorSurfaceNeutralNearer: '#ffffff',
  colorSurfaceNeutralTranslucent: '#ffffff80',
  colorBackgroundNeutralHeavy: '#616161',
  colorBackgroundNeutralLoud: '#616161',
  colorBackgroundNeutralSoft: '#0000001a',
  colorBackgroundNeutralSubtle: '#00000000',
  colorBackgroundNeutralTransparent: '#00000000',
  colorBackgroundNeutralTranslucent: '#ffffff80',
  colorBackgroundBrandHeavy: '#185abd',
  colorBackgroundBrandLoud: '#185abd',
  colorBackgroundBrandSoft: '#d2e0f4',
  colorBackgroundBrandSubtle: '#d2e0f4',
  colorBackgroundBrandTransparent: '#00000000',
  colorBackgroundDangerLoud: '#d13438',
  colorBackgroundDangerSoft: '#f1bbbc',
  colorBackgroundDangerSubtle: '#fdf6f6',
  colorBackgroundWarningLoud: '#fde300',
  colorBackgroundWarningSoft: '#fef7b2',
  colorBackgroundWarningSubtle: '#fffef5',
  colorBackgroundSuccessLoud: '#107c10',
  colorBackgroundSuccessSoft: '#9fd89f',
  colorBackgroundSuccessSubtle: '#f1faf1',
  colorStrokeNeutralHeavy: '#616161',
  colorStrokeNeutralLoud: '#d1d1d1',
  colorStrokeNeutralSoft: '#d1d1d1',
  colorStrokeNeutralSubtle: '#e0e0e0',
  colorStrokeNeutralTransparent: '#00000000',
  colorStrokeNeutralOnloud: '#ffffff',
  colorStrokeBrandLoud: '#185abd',
  colorStrokeBrandSoft: '#185abd',
  colorStrokeBrandSubtle: '#6794d7',
  colorStrokeBrandOnloud: '#ffffff',
  colorStrokeDangerLoud: '#d13438',
  colorStrokeDangerSoft: '#f1bbbc',
  colorStrokeDangerSubtle: '#f1bbbc',
  colorStrokeDangerOnloud: '#ffffff',
  colorStrokeWarningLoud: '#fde300',
  colorStrokeWarningSoft: '#fef7b2',
  colorStrokeWarningSubtle: '#fef7b2',
  colorStrokeWarningOnloud: '#ffffff',
  colorStrokeSuccessLoud: '#107c10',
  colorStrokeSuccessSoft: '#9fd89f',
  colorStrokeSuccessSubtle: '#9fd89f',
  colorStrokeSuccessOnloud: '#ffffff',
  colorForegroundNeutralPrimary: '#242424',
  colorForegroundNeutralSecondary: '#424242',
  colorForegroundNeutralTertiary: '#616161',
  colorForegroundNeutralOnloud: '#ffffff',
  colorForegroundBrandPrimary: '#185abd',
  colorForegroundBrandOnloud: '#ffffff',
  colorForegroundDangerPrimary: '#bc2f32',
  colorForegroundDangerOnloud: '#ffffff',
  colorForegroundWarningPrimary: '#817400',
  colorForegroundWarningOnloud: '#ffffff',
  colorForegroundSuccessPrimary: '#0e700e',
  colorForegroundSuccessOnloud: '#ffffff',
  colorFixedWhite: '#ffffff',
  colorFixedBlack: '#000000',
  colorExpressionAccentHeavy: '#242424',
  colorExpressionAccentLoud: '#707070',
  colorExpressionAccentSoft: '#0000001a',
  colorExpressionAccentSubtle: '#0000000d',
  colorExpressionAchromaticHeavy: '#000000',
  colorExpressionAchromaticSubtle: '#ffffff',
  colorExpressionGrayHeavy: '#474747',
  colorExpressionGrayLoud: '#949494',
  colorExpressionGraySoft: '#e0e0e0',
  colorExpressionGraySubtle: '#f5f5f5',
  colorExpressionNavyHeavy: '#001e89',
  colorExpressionNavyLoud: '#546fd2',
  colorExpressionNavySoft: '#ccd5f3',
  colorExpressionNavySubtle: '#f2f4fc',
  colorExpressionBlueHeavy: '#004377',
  colorExpressionBlueLoud: '#3595de',
  colorExpressionBlueSoft: '#d0e7f8',
  colorExpressionBlueSubtle: '#f3f9fd',
  colorExpressionGreenHeavy: '#0c5e0c',
  colorExpressionGreenLoud: '#54b054',
  colorExpressionGreenSoft: '#c9eac9',
  colorExpressionGreenSubtle: '#f1faf1',
  colorExpressionLimeHeavy: '#405f14',
  colorExpressionLimeLoud: '#689920',
  colorExpressionLimeSoft: '#cfe5af',
  colorExpressionLimeSubtle: '#e5f1d3',
  colorExpressionYellowHeavy: '#4c4400',
  colorExpressionYellowLoud: '#fde300',
  colorExpressionYellowSoft: '#feee66',
  colorExpressionYellowSubtle: '#fef7b2',
  colorExpressionPumpkinHeavy: '#712d09',
  colorExpressionPumpkinLoud: '#df8e64',
  colorExpressionPumpkinSoft: '#f7dfd2',
  colorExpressionPumpkinSubtle: '#fdf7f4',
  colorExpressionRedHeavy: '#751d1f',
  colorExpressionRedLoud: '#dc5e62',
  colorExpressionRedSoft: '#f8dadb',
  colorExpressionRedSubtle: '#fdf6f6',
  colorExpressionPinkHeavy: '#80215d',
  colorExpressionPinkLoud: '#e750b0',
  colorExpressionPinkSoft: '#f7c0e3',
  colorExpressionPinkSubtle: '#fef6fb',
  colorExpressionPurpleHeavy: '#532982',
  colorExpressionPurpleLoud: '#9470bd',
  colorExpressionPurpleSoft: '#e0d3ed',
  colorExpressionPurpleSubtle: '#f7f4fb',
  colorOverlayNeutralTranslucent: '#ffffff80',
  colorMaterialBackgroundThick: '#ffffffe6',
  colorMaterialBackgroundRegular: '#ffffffcc',
  colorMaterialBackgroundThin: '#ffffff80',
  colorBackgroundNeutralDisabled: '#f0f0f0',
  colorBackgroundNeutralHeavyDisabled: '#f0f0f0',
  colorBackgroundNeutralSubtleDisabled: '#f0f0f0',
  colorStrokeNeutralDisabled: '#e0e0e0',
  colorForegroundNeutralDisabled: '#bdbdbd',
  colorStrokeFocusInner: '#ffffff',
  colorStrokeFocusOuter: '#000000',
  colorShadow: '#000000',
  shadowLowest: {
    ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
    key: { color: '#00000024', x: 0, y: 1, blur: 2 },
  },
  shadowLower: {
    ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
    key: { color: '#00000024', x: 0, y: 2, blur: 4 },
  },
  shadowLow: {
    ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
    key: { color: '#00000024', x: 0, y: 4, blur: 8 },
  },
  shadowHigh: {
    ambient: { color: '#0000001f', x: 0, y: 0, blur: 2 },
    key: { color: '#00000024', x: 0, y: 8, blur: 16 },
  },
  shadowHigher: {
    ambient: { color: '#00000033', x: 0, y: 0, blur: 8 },
    key: { color: '#0000003d', x: 0, y: 14, blur: 28 },
  },
  shadowHighest: {
    ambient: { color: '#00000033', x: 0, y: 0, blur: 8 },
    key: { color: '#0000003d', x: 0, y: 32, blur: 64 },
  },
  hover: {
    colorSurfaceNeutralFarther: '#f5f5f5',
    colorSurfaceNeutralFar: '#ebebeb',
    colorSurfaceNeutralNear: '#f0f0f0',
    colorSurfaceNeutralNearer: '#f5f5f5',
    colorSurfaceNeutralTranslucent: '#ffffff80',
    colorBackgroundNeutralHeavy: '#616161',
    colorBackgroundNeutralLoud: '#616161',
    colorBackgroundNeutralSoft: '#0000001a',
    colorBackgroundNeutralSubtle: '#f5f5f5',
    colorBackgroundNeutralTransparent: '#00000000',
    colorBackgroundNeutralTranslucent: '#ffffff80',
    colorBackgroundBrandHeavy: '#1651aa',
    colorBackgroundBrandLoud: '#1651aa',
    colorBackgroundBrandSoft: '#d2e0f4',
    colorBackgroundBrandSubtle: '#d2e0f4',
    colorBackgroundBrandTransparent: '#00000000',
    colorBackgroundDangerLoud: '#d13438',
    colorBackgroundDangerSoft: '#f1bbbc',
    colorBackgroundDangerSubtle: '#fdf6f6',
    colorBackgroundWarningLoud: '#fde300',
    colorBackgroundWarningSoft: '#fef7b2',
    colorBackgroundWarningSubtle: '#fffef5',
    colorBackgroundSuccessLoud: '#107c10',
    colorBackgroundSuccessSoft: '#9fd89f',
    colorBackgroundSuccessSubtle: '#f1faf1',
    colorStrokeNeutralHeavy: '#575757',
    colorStrokeNeutralLoud: '#c7c7c7',
    colorStrokeNeutralSoft: '#c7c7c7',
    colorStrokeNeutralSubtle: '#e0e0e0',
    colorStrokeNeutralTransparent: '#00000000',
    colorStrokeNeutralOnloud: '#ffffff',
    colorStrokeBrandLoud: '#185abd',
    colorStrokeBrandSoft: '#185abd',
    colorStrokeBrandSubtle: '#6794d7',
    colorStrokeBrandOnloud: '#ffffff',
    colorStrokeDangerLoud: '#d13438',
    colorStrokeDangerSoft: '#f1bbbc',
    colorStrokeDangerSubtle: '#f1bbbc',
    colorStrokeDangerOnloud: '#ffffff',
    colorStrokeWarningLoud: '#fde300',
    colorStrokeWarningSoft: '#fef7b2',
    colorStrokeWarningSubtle: '#fef7b2',
    colorStrokeWarningOnloud: '#ffffff',
    colorStrokeSuccessLoud: '#107c10',
    colorStrokeSuccessSoft: '#9fd89f',
    colorStrokeSuccessSubtle: '#9fd89f',
    colorStrokeSuccessOnloud: '#ffffff',
    colorForegroundNeutralPrimary: '#242424',
    colorForegroundNeutralSecondary: '#242424',
    colorForegroundNeutralTertiary: '#424242',
    colorForegroundNeutralOnloud: '#ffffff',
    colorForegroundBrandPrimary: '#185abd',
    colorForegroundBrandOnloud: '#ffffff',
    colorForegroundDangerPrimary: '#bc2f32',
    colorForegroundDangerOnloud: '#ffffff',
    colorForegroundWarningPrimary: '#817400',
    colorForegroundWarningOnloud: '#ffffff',
    colorForegroundSuccessPrimary: '#0e700e',
    colorForegroundSuccessOnloud: '#ffffff',
  },
  pressed: {
    colorSurfaceNeutralFarther: '#f0f0f0',
    colorSurfaceNeutralFar: '#d6d6d6',
    colorSurfaceNeutralNear: '#dbdbdb',
    colorSurfaceNeutralNearer: '#e0e0e0',
    colorSurfaceNeutralTranslucent: '#ffffff80',
    colorBackgroundNeutralHeavy: '#616161',
    colorBackgroundNeutralLoud: '#616161',
    colorBackgroundNeutralSoft: '#0000001a',
    colorBackgroundNeutralSubtle: '#e0e0e0',
    colorBackgroundNeutralTransparent: '#00000000',
    colorBackgroundNeutralTranslucent: '#ffffff80',
    colorBackgroundBrandHeavy: '#0e336a',
    colorBackgroundBrandLoud: '#0e336a',
    colorBackgroundBrandSoft: '#d2e0f4',
    colorBackgroundBrandSubtle: '#d2e0f4',
    colorBackgroundBrandTransparent: '#00000000',
    colorBackgroundDangerLoud: '#d13438',
    colorBackgroundDangerSoft: '#f1bbbc',
    colorBackgroundDangerSubtle: '#fdf6f6',
    colorBackgroundWarningLoud: '#fde300',
    colorBackgroundWarningSoft: '#fef7b2',
    colorBackgroundWarningSubtle: '#fffef5',
    colorBackgroundSuccessLoud: '#107c10',
    colorBackgroundSuccessSoft: '#9fd89f',
    colorBackgroundSuccessSubtle: '#f1faf1',
    colorStrokeNeutralHeavy: '#4d4d4d',
    colorStrokeNeutralLoud: '#b3b3b3',
    colorStrokeNeutralSoft: '#b3b3b3',
    colorStrokeNeutralSubtle: '#e0e0e0',
    colorStrokeNeutralTransparent: '#00000000',
    colorStrokeNeutralOnloud: '#ffffff',
    colorStrokeBrandLoud: '#185abd',
    colorStrokeBrandSoft: '#185abd',
    colorStrokeBrandSubtle: '#6794d7',
    colorStrokeBrandOnloud: '#ffffff',
    colorStrokeDangerLoud: '#d13438',
    colorStrokeDangerSoft: '#f1bbbc',
    colorStrokeDangerSubtle: '#f1bbbc',
    colorStrokeDangerOnloud: '#ffffff',
    colorStrokeWarningLoud: '#fde300',
    colorStrokeWarningSoft: '#fef7b2',
    colorStrokeWarningSubtle: '#fef7b2',
    colorStrokeWarningOnloud: '#ffffff',
    colorStrokeSuccessLoud: '#107c10',
    colorStrokeSuccessSoft: '#9fd89f',
    colorStrokeSuccessSubtle: '#9fd89f',
    colorStrokeSuccessOnloud: '#ffffff',
    colorForegroundNeutralPrimary: '#242424',
    colorForegroundNeutralSecondary: '#242424',
    colorForegroundNeutralTertiary: '#424242',
    colorForegroundNeutralOnloud: '#ffffff',
    colorForegroundBrandPrimary: '#185abd',
    colorForegroundBrandOnloud: '#ffffff',
    colorForegroundDangerPrimary: '#bc2f32',
    colorForegroundDangerOnloud: '#ffffff',
    colorForegroundWarningPrimary: '#817400',
    colorForegroundWarningOnloud: '#ffffff',
    colorForegroundSuccessPrimary: '#0e700e',
    colorForegroundSuccessOnloud: '#ffffff',
  },
};
