import type { ImageProps } from 'react-native';

import type { ITextWin32Props, IViewWin32Props } from '@office-iss/react-native-win32';

import type { IFilterMask } from './filter.types';

// export core interface types
export type ITextProps = ITextWin32Props;
export type IViewProps = IViewWin32Props;
export type IImageProps = ImageProps;

const _viewMask: IFilterMask<IViewProps> = {
  children: true,
  accessible: true,
  accessibilityAccessKey: true,
  accessibilityActions: true,
  accessibilityAnnotation: true,
  accessibilityControls: true,
  accessibilityDescription: true,
  accessibilityDescribedBy: true,
  accessibilityItemType: true,
  accessibilityLabel: true,
  accessibilityLabelledBy: true,
  accessibilityLevel: true,
  accessibilityPositionInSet: true,
  accessibilityRole: true,
  accessibilitySetSize: true,
  accessibilityState: true,
  accessibilityHint: true,
  accessibilityValue: true,
  animationClass: true,
  cursor: true,
  enableFocusRing: true,
  hitSlop: true,
  onLayout: true,
  pointerEvents: true,
  removeClippedSubviews: true,
  style: true,
  testID: true,
  nativeID: true,
  keyDownEvents: true,
  keyUpEvents: true,
  onBlur: true,
  onBlurCapture: true,
  onFocus: true,
  onFocusCapture: true,
  onKeyDown: true,
  onKeyDownCapture: true,
  onKeyUp: true,
  onKeyUpCapture: true,
  onMouseEnter: true,
  onMouseLeave: true,
  onStartShouldSetResponder: true,
  onStartShouldSetResponderCapture: true,
  onMoveShouldSetResponder: true,
  onMoveShouldSetResponderCapture: true,
  onResponderEnd: true,
  onResponderGrant: true,
  onResponderMove: true,
  onResponderReject: true,
  onAccessibilityAction: true,
  onAccessibilityTap: true,
  onResponderRelease: true,
  onResponderStart: true,
  onResponderTerminate: true,
  onResponderTerminationRequest: true,
  onTouchCancel: true,
  onTouchEnd: true,
  onTouchEndCapture: true,
  onTouchMove: true,
  onTouchStart: true,
  tooltip: true,
  focusable: true,
  id: false,
  'aria-label': false,
  'aria-busy': false,
  'aria-checked': false,
  'aria-disabled': false,
  'aria-expanded': false,
  'aria-selected': false,
  'aria-labelledby': false,
  'aria-valuemax': false,
  'aria-valuemin': false,
  'aria-valuenow': false,
  'aria-valuetext': false,
  'aria-hidden': false,
  'aria-live': false,
  'aria-modal': false,
  role: false,
  onPointerEnter: false,
  onPointerEnterCapture: false,
  onPointerLeave: false,
  onPointerLeaveCapture: false,
  onPointerMove: false,
  onPointerMoveCapture: false,
  onPointerCancel: false,
  onPointerCancelCapture: false,
  onPointerDown: false,
  onPointerDownCapture: false,
  onPointerUp: false,
  onPointerUpCapture: false,
  collapsable: true,
  needsOffscreenAlphaCompositing: true,
  renderToHardwareTextureAndroid: true,
  shouldRasterizeIOS: true,
  isTVSelectable: false,
  hasTVPreferredFocus: false,
  tvParallaxProperties: false,
  tvParallaxShiftDistanceX: false,
  tvParallaxShiftDistanceY: false,
  tvParallaxTiltAngle: false,
  tvParallaxMagnification: false,
  tabIndex: true,
  importantForAccessibility: true,
  accessibilityLiveRegion: true,
  accessibilityElementsHidden: true,
  accessibilityViewIsModal: false,
  onAccessibilityEscape: false,
  onMagicTap: false,
  accessibilityIgnoresInvertColors: false,
  accessibilityLanguage: false,
};

const _textMask: IFilterMask<ITextProps> = {
  children: true,
  accessibilityAccessKey: true,
  accessibilityActions: true,
  accessibilityAnnotation: true,
  accessibilityControls: true,
  accessibilityDescribedBy: true,
  accessibilityDescription: true,
  accessibilityHint: true,
  accessibilityItemType: true,
  accessibilityLabel: true,
  accessibilityLabelledBy: true,
  accessibilityLevel: true,
  accessibilityPositionInSet: true,
  accessibilityRole: true,
  accessibilitySetSize: true,
  accessibilityState: true,
  accessibilityValue: true,
  accessible: true,
  onAccessibilityAction: true,
  onAccessibilityTap: true,
  testID: true,
  allowFontScaling: true,
  ellipsizeMode: true,
  lineBreakMode: true,
  numberOfLines: true,
  keyDownEvents: true,
  keyUpEvents: true,
  onKeyDown: true,
  onKeyDownCapture: true,
  onKeyUp: true,
  onKeyUpCapture: true,
  onLayout: true,
  onLongPress: true,
  onPress: true,
  onPressIn: true,
  onPressOut: true,
  onTextLayout: true,
  style: true,
  selectable: true,
  nativeID: true,
  maxFontSizeMultiplier: true,
  textStyle: true,
  tooltip: true,
  focusable: true,
  onBlur: true,
  onBlurCapture: true,
  onFocus: true,
  onFocusCapture: true,
  id: false,
  'aria-label': false,
  'aria-busy': false,
  'aria-checked': false,
  'aria-disabled': false,
  'aria-expanded': false,
  'aria-selected': false,
  'aria-labelledby': false,
  'aria-valuemax': false,
  'aria-valuemin': false,
  'aria-valuenow': false,
  'aria-valuetext': false,
  'aria-hidden': false,
  'aria-live': false,
  'aria-modal': false,
  role: false,
  adjustsFontSizeToFit: false,
  dynamicTypeRamp: false,
  minimumFontScale: false,
  suppressHighlighting: false,
  disabled: true,
  selectionColor: true,
  textBreakStrategy: true,
  dataDetectorType: false,
  android_hyphenationFrequency: false,
  importantForAccessibility: true,
  accessibilityLiveRegion: true,
  accessibilityElementsHidden: true,
  accessibilityViewIsModal: false,
  onAccessibilityEscape: false,
  onMagicTap: false,
  accessibilityIgnoresInvertColors: false,
  accessibilityLanguage: false,
};

const _imageMask: IFilterMask<IImageProps> = {
  children: true,
  accessibilityActions: true,
  accessibilityElementsHidden: true,
  accessibilityHint: true,
  accessibilityIgnoresInvertColors: true,
  accessibilityLabel: true,
  accessibilityLiveRegion: true,
  accessibilityRole: true,
  accessibilityState: true,
  accessibilityValue: true,
  accessibilityViewIsModal: true,
  accessible: true,
  onAccessibilityAction: true,
  onAccessibilityEscape: true,
  onAccessibilityTap: true,
  importantForAccessibility: true,
  style: true,
  onError: true,
  onLayout: true,
  onLoad: true,
  onLoadEnd: true,
  onLoadStart: true,
  onMagicTap: true,
  onPartialLoad: true,
  onProgress: true,
  borderBottomLeftRadius: true,
  borderBottomRightRadius: true,
  borderRadius: true,
  borderTopLeftRadius: true,
  borderTopRightRadius: true,
  progressiveRenderingEnabled: true,
  source: true,
  resizeMethod: true,
  resizeMode: true,
  loadingIndicatorSource: true,
  testID: true,
  defaultSource: true,
  blurRadius: true,
  capInsets: true,
  fadeDuration: true,
  nativeID: true,
  id: false,
  alt: false,
  'aria-label': false,
  'aria-busy': false,
  'aria-checked': false,
  'aria-disabled': false,
  'aria-expanded': false,
  'aria-selected': false,
  'aria-labelledby': false,
  'aria-valuemax': false,
  'aria-valuemin': false,
  'aria-valuenow': false,
  'aria-valuetext': false,
  'aria-hidden': false,
  'aria-live': false,
  'aria-modal': false,
  role: false,
  accessibilityLabelledBy: false,
  accessibilityLanguage: false,
};

export function filterViewProps(propName: string): boolean {
  return _viewMask[propName];
}

export function filterTextProps(propName: string): boolean {
  return _textMask[propName];
}

export function filterImageProps(propName: string): boolean {
  return _imageMask[propName];
}
