export const HOMEPAGE_BADGE_BUTTON = 'Homepage_Badge_Button';
export const BADGE_TESTPAGE = 'Badge_TestPage';

export const BADGE_TEST_COMPONENT = 'BADGE_TEST_COMPONENT';
export const BADGE_SECONDARY_TEST_COMPONENT = 'BADGE_SECONDARY_TEST_COMPONENT';

export const COUNTER_BADGE_TEST_COMPONENT = 'COUNTER_BADGE_TEST_COMPONENT';
export const COUNTER_BADGE_SECONDARY_TEST_COMPONENT = 'COUNTER_BADGE_SECONDARY_TEST_COMPONENT';
export const COUNTER_BADGE_TERTIARY_COMPONENT = 'COUNTER_BADGE_TERTIARY_COMPONENT';
