// This package is a compatibility shim. The theme type definitions now live in
// the `@fluentui-react-native/design` package and are exposed via its `/theming`
// submodule. These re-exports preserve the existing `@fluentui-react-native/theme-types`
// entry point for backwards compatibility.
export type {
  AliasColorTokens,
  AppearanceOptions,
  BaseShadowAliasTokens,
  Color,
  FabricWebPalette,
  FontDynamicTypeRamp,
  FontFamilies,
  FontFamily,
  FontFamilyValue,
  FontSize,
  FontSizeValuePoints,
  FontSizes,
  FontWeight,
  FontWeightValue,
  FontWeights,
  OfficePalette,
  Palette,
  PaletteBackgroundColors,
  PaletteTextColors,
  PartialPalette,
  PartialShadowDefinition,
  PartialTheme,
  PartialTypography,
  ShadowToken,
  ShadowValue,
  Spacing,
  TextStyling,
  Theme,
  ThemeColorDefinition,
  ThemeOptions,
  ThemeShadowDefinition,
  Typography,
  Variant,
  VariantValue,
  Variants,
} from '@fluentui-react-native/design/theming';
export { ThemeContext, useTheme } from '@fluentui-react-native/design/theming';
