backend:
  name: github
  repo: microsoft/fluent-site
  branch: master
  open_authoring: true

local_backend: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: components
    extension: 'mdx'
    format: 'frontmatter'
    label: Components
    folder: packages/fluent-website/docs/components
    create: true
    fields:
      - { name: title, label: Title }
      - { name: titleCategory, label: Category before title }
      - { name: body, label: Body, widget: markdown }
  - label: 'Styles'
    name: 'styles'
    extension: 'mdx'
    create: true
    format: 'frontmatter'
    folder:  packages/fluent-website/docs/styles
    fields:
      - { name: title, label: Title }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title'],
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
  - label: 'Categories'
    name: 'categories'
    folder: 'fluent-website/categories'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string }
