require_relative '../../../node_modules/react-native-test-app/macos/test_app'

workspace 'FluentTester.xcworkspace'

react_native_path = "#{__dir__}/../../../node_modules/react-native"

use_test_app! do |target|
  target.app do
    platform :osx, '12'

    # There is a bug where autolinking isn't working, do specify these manually.
    pod 'FRNAvatar', :path => '../../../packages/experimental/Avatar/FRNAvatar.podspec'
    pod 'FRNCallout', :path => '../../../packages/components/Callout/FRNCallout.podspec'
    pod 'FRNCheckbox', :path => '../../../packages/experimental/Checkbox/FRNCheckbox.podspec'
    pod 'FRNMenuButton', :path => '../../../packages/components/MenuButton/FRNMenuButton.podspec'
    pod 'FRNRadioButton', :path => '../../../packages/components/RadioGroup/FRNRadioButton.podspec'
    pod 'RCTFocusZone', :path => '../../../packages/components/FocusZone/RCTFocusZone.podspec'
  end
end
