// `storybook.requires` is generated by the `withStorybook` metro wrapper (or the
// `storybook-generate` script) from the `main.ts` stories glob. It is git-ignored.
import { useEffect, useState } from 'react';
import { View, StyleSheet } from 'react-native';
import { addons } from 'storybook/preview-api';
import { view } from './storybook.requires';
import { LiteUI } from '@storybook/react-native-ui-lite';
import { DesktopTestControls } from './DesktopTestControls';
import { useDesktopTestHost } from './useDesktopTestHost';
import { StorybookThemeHost } from './StorybookTheme';
import { desktopRuntime } from '../desktop-tests/generated/desktop-runtime.generated';

// We run Storybook in lite mode: the heavy default on-device UI (`@storybook/react-native-ui`,
// which needs reanimated/gesture-handler/etc.) is not bundled. `getStorybookUI` would otherwise
// try to render its `FullUI` (which is mocked out and therefore `undefined`, causing an
// "Element type is invalid" crash), so we provide the lightweight `LiteUI` as the UI component.

// Simple in-memory storage so Storybook doesn't warn about a missing `storage` (we intentionally
// avoid @react-native-async-storage/async-storage, which is another native module). The selected
// story just won't persist across full reloads.
const memoryStore: Record<string, string> = {};
const storage = {
  getItem: async (key: string) => (key in memoryStore ? memoryStore[key] : null),
  setItem: async (key: string, value: string) => {
    memoryStore[key] = value;
  },
};

// `enableWebsockets` + `host`/`port` connect the app to the desktop host
// (`yarn desktop:host:<platform>`, default ws://127.0.0.1:7007). The host owns Storybook control,
// MCP, and desktop test coordination. If it is absent the app still works without those services.
const StorybookUI = view.getStorybookUI({
  enableWebsockets: true,
  host: desktopRuntime.channel.host,
  port: desktopRuntime.channel.port,
  CustomUIComponent: LiteUI,
  storage,
});

/**
 * Tracks the rendered story so "Run current test" always targets what is on screen.
 *
 * The channel event carries only a story id; nothing executable crosses this boundary.
 */
const useCurrentStoryId = (): string | undefined => {
  const [storyId, setStoryId] = useState<string | undefined>();

  useEffect(() => {
    let channel: ReturnType<typeof addons.getChannel> | undefined;
    try {
      channel = addons.getChannel();
    } catch {
      // The preview channel is not available in every host; the controls degrade to "Run all".
      return undefined;
    }
    const onRendered = (id: string) => setStoryId(id);
    channel.on('storyRendered', onRendered);
    return () => {
      channel?.off('storyRendered', onRendered);
    };
  }, []);

  return storyId;
};

const StorybookApp = () => {
  const currentStoryId = useCurrentStoryId();
  // The desktop host announces itself over the Storybook channel.
  const desktopHost = useDesktopTestHost(desktopRuntime);

  return (
    <StorybookThemeHost>
      <View style={styles.root}>
        <View style={styles.preview}>
          <StorybookUI />
        </View>
        <DesktopTestControls currentStoryId={currentStoryId} host={desktopHost} />
      </View>
    </StorybookThemeHost>
  );
};

const styles = StyleSheet.create({
  preview: {
    flex: 1,
  },
  root: {
    flex: 1,
  },
});

export default StorybookApp;
