// `storybook.requires` is generated by the `withStorybook` metro wrapper (or the
// `storybook-generate` script) from the `main.ts` stories glob. It is git-ignored.
import { view } from './storybook.requires';
import { StorybookThemeHost } from './StorybookTheme';
import { StorybookUIComponent } from './StorybookUI';

// We run Storybook in lite mode: the heavy default on-device UI (`@storybook/react-native-ui`,
// which needs reanimated/gesture-handler/etc.) is not bundled. StorybookUI resolves to LiteUI on
// macOS and Windows and to the channel-driven preview surface on Win32.

// Simple in-memory storage so Storybook doesn't warn about a missing `storage` (we intentionally
// avoid @react-native-async-storage/async-storage, which is another native module). The selected
// story just won't persist across full reloads.
const memoryStore: Record<string, string> = {};
const storage = {
  getItem: async (key: string) => (key in memoryStore ? memoryStore[key] : null),
  setItem: async (key: string, value: string) => {
    memoryStore[key] = value;
  },
};

// `enableWebsockets` + `host`/`port` connect the app to the standalone Storybook channel server
// (`yarn storybook-server`, default ws://127.0.0.1:7007). This lets external agents drive the app —
// select stories, read/update control args — and powers the MCP endpoint. If the server isn't
// running the transport just logs a connection error; the app still works standalone.
const StorybookUI = view.getStorybookUI({
  enableWebsockets: true,
  host: '127.0.0.1',
  port: 7007,
  CustomUIComponent: StorybookUIComponent,
  storage,
});

const StorybookApp = () => (
  <StorybookThemeHost>
    <StorybookUI />
  </StorybookThemeHost>
);

export default StorybookApp;
