# Switching between node-modules mode and pnpm mode requires changing how relative paths are handled.

# (pnpm mode) allow modules to resolve correctly in upstream podfiles
ENV['REACT_NATIVE_NODE_MODULES_DIR'] = File.join(__dir__, '../node_modules')

# (pnpm mode)
require_relative '../node_modules/react-native-test-app/macos/test_app'

workspace 'AgenticStorybook.xcworkspace'

# (pnpm mode)
react_native_path = "#{__dir__}/../node_modules/react-native"

use_test_app!(:fabric_enabled => true, :bridgeless_enabled => false) do |target|
  target.app do
    platform :osx, '14'
  end
end
