/**
 * WARNING: This file is auto-generated. Do not edit it manually.
 */

import type { Theme } from '../../theming/types/Theme.types';
import { omitUndefinedProperties } from './omitUndefinedProperties';

export function projectThemeToFlex(theme: Theme) {
  const { colors, shadows, typography } = theme;
  const buttonTokens = (theme.components?.Button as { tokens?: { borderRadius?: number } } | undefined)?.tokens;
  return omitUndefinedProperties({
    ...(buttonTokens?.borderRadius === undefined ? {} : { borderRadius: {
      base200: buttonTokens?.borderRadius,
      base300: buttonTokens?.borderRadius,
    } }),
    color: {
      backgroundBrandHeavy: colors?.brandBackground,
      backgroundBrandLoud: colors?.compoundBrandBackground1,
      backgroundBrandSoft: colors?.brandBackground2,
      backgroundBrandSubtle: colors?.brandBackground2,
      backgroundBrandTransparent: colors?.transparentBackground,
      backgroundDangerLoud: colors?.dangerBackground3,
      backgroundDangerSoft: colors?.dangerBackground2,
      backgroundDangerSubtle: colors?.dangerBackground1,
      backgroundNeutralDisabled: colors?.neutralBackgroundDisabled,
      backgroundNeutralHeavy: colors?.neutralBackgroundInverted,
      backgroundNeutralHeavyDisabled: colors?.neutralBackgroundDisabled,
      backgroundNeutralLoud: colors?.neutralBackgroundInverted,
      backgroundNeutralSubtle: colors?.neutralBackground2,
      backgroundNeutralSubtleDisabled: colors?.neutralBackgroundDisabled,
      backgroundNeutralTransparent: colors?.transparentBackground,
      backgroundSuccessLoud: colors?.successBackground3,
      backgroundSuccessSoft: colors?.successBackground2,
      backgroundSuccessSubtle: colors?.successBackground1,
      backgroundWarningLoud: colors?.warningBackground3,
      backgroundWarningSoft: colors?.warningBackground2,
      backgroundWarningSubtle: colors?.warningBackground1,
      expressionAchromaticHeavy: colors?.black,
      expressionAchromaticSubtle: colors?.white,
      fixedBlack: colors?.black,
      fixedWhite: colors?.white,
      foregroundBrandOnloud: colors?.neutralForegroundOnBrand,
      foregroundBrandPrimary: colors?.brandForeground1,
      foregroundDangerOnloud: colors?.neutralForegroundOnBrand,
      foregroundDangerPrimary: colors?.dangerForeground1,
      foregroundNeutralDisabled: colors?.neutralForegroundDisabled,
      foregroundNeutralOnloud: colors?.neutralForegroundOnBrand,
      foregroundNeutralPrimary: colors?.neutralForeground1,
      foregroundNeutralSecondary: colors?.neutralForeground2,
      foregroundNeutralTertiary: colors?.neutralForeground3,
      foregroundSuccessOnloud: colors?.neutralForegroundOnBrand,
      foregroundSuccessPrimary: colors?.successForeground1,
      foregroundWarningOnloud: colors?.neutralForegroundOnBrand,
      foregroundWarningPrimary: colors?.warningForeground1,
      hover: {
        backgroundBrandHeavy: colors?.brandBackgroundHover,
        backgroundBrandLoud: colors?.compoundBrandBackground1Hover,
        backgroundBrandTransparent: colors?.transparentBackgroundHover,
        backgroundNeutralSubtle: colors?.neutralBackground2Hover,
        backgroundNeutralTransparent: colors?.transparentBackgroundHover,
        foregroundBrandOnloud: colors?.neutralForegroundOnBrandHover,
        foregroundDangerOnloud: colors?.neutralForegroundOnBrandHover,
        foregroundNeutralOnloud: colors?.neutralForegroundOnBrandHover,
        foregroundNeutralPrimary: colors?.neutralForeground1Hover,
        foregroundNeutralSecondary: colors?.neutralForeground2Hover,
        foregroundNeutralTertiary: colors?.neutralForeground3Hover,
        foregroundSuccessOnloud: colors?.neutralForegroundOnBrandHover,
        foregroundWarningOnloud: colors?.neutralForegroundOnBrandHover,
        strokeBrandOnloud: colors?.neutralForegroundOnBrandHover,
        strokeDangerOnloud: colors?.neutralForegroundOnBrandHover,
        strokeNeutralHeavy: colors?.neutralStrokeAccessibleHover,
        strokeNeutralLoud: colors?.neutralStroke1Hover,
        strokeNeutralOnloud: colors?.neutralForegroundOnBrandHover,
        strokeNeutralSoft: colors?.neutralStroke1Hover,
        strokeNeutralTransparent: colors?.transparentStrokeInteractive,
        strokeSuccessOnloud: colors?.neutralForegroundOnBrandHover,
        strokeWarningOnloud: colors?.neutralForegroundOnBrandHover,
        surfaceNeutralFar: colors?.neutralBackground3Hover,
        surfaceNeutralFarther: colors?.neutralBackground5Hover,
        surfaceNeutralNear: colors?.neutralBackground2Hover,
        surfaceNeutralNearer: colors?.neutralBackground1Hover,
      },
      pressed: {
        backgroundBrandHeavy: colors?.brandBackgroundPressed,
        backgroundBrandLoud: colors?.compoundBrandBackground1Pressed,
        backgroundBrandTransparent: colors?.transparentBackgroundPressed,
        backgroundNeutralSubtle: colors?.neutralBackground2Pressed,
        backgroundNeutralTransparent: colors?.transparentBackgroundPressed,
        foregroundBrandOnloud: colors?.neutralForegroundOnBrandPressed,
        foregroundDangerOnloud: colors?.neutralForegroundOnBrandPressed,
        foregroundNeutralOnloud: colors?.neutralForegroundOnBrandPressed,
        foregroundNeutralPrimary: colors?.neutralForeground1Pressed,
        foregroundNeutralSecondary: colors?.neutralForeground2Pressed,
        foregroundNeutralTertiary: colors?.neutralForeground3Pressed,
        foregroundSuccessOnloud: colors?.neutralForegroundOnBrandPressed,
        foregroundWarningOnloud: colors?.neutralForegroundOnBrandPressed,
        strokeBrandOnloud: colors?.neutralForegroundOnBrandPressed,
        strokeDangerOnloud: colors?.neutralForegroundOnBrandPressed,
        strokeNeutralHeavy: colors?.neutralStrokeAccessiblePressed,
        strokeNeutralLoud: colors?.neutralStroke1Pressed,
        strokeNeutralOnloud: colors?.neutralForegroundOnBrandPressed,
        strokeNeutralSoft: colors?.neutralStroke1Pressed,
        strokeSuccessOnloud: colors?.neutralForegroundOnBrandPressed,
        strokeWarningOnloud: colors?.neutralForegroundOnBrandPressed,
        surfaceNeutralFar: colors?.neutralBackground3Pressed,
        surfaceNeutralFarther: colors?.neutralBackground5Pressed,
        surfaceNeutralNear: colors?.neutralBackground2Pressed,
        surfaceNeutralNearer: colors?.neutralBackground1Pressed,
      },
      shadow: colors?.black,
      strokeBrandLoud: colors?.brandStroke1,
      strokeBrandOnloud: colors?.neutralForegroundOnBrand,
      strokeBrandSoft: colors?.brandStroke1,
      strokeBrandSubtle: colors?.brandStroke2,
      strokeDangerLoud: colors?.dangerBorder2,
      strokeDangerOnloud: colors?.neutralForegroundOnBrand,
      strokeDangerSoft: colors?.dangerBorder1,
      strokeDangerSubtle: colors?.dangerBorder1,
      strokeFocusInner: colors?.strokeFocus1,
      strokeFocusOuter: colors?.strokeFocus2,
      strokeNeutralDisabled: colors?.neutralStrokeDisabled,
      strokeNeutralHeavy: colors?.neutralStrokeAccessible,
      strokeNeutralLoud: colors?.neutralStroke1,
      strokeNeutralOnloud: colors?.neutralForegroundOnBrand,
      strokeNeutralSoft: colors?.neutralStroke1,
      strokeNeutralSubtle: colors?.neutralStroke2,
      strokeNeutralTransparent: colors?.transparentStroke,
      strokeSuccessLoud: colors?.successBorder2,
      strokeSuccessOnloud: colors?.neutralForegroundOnBrand,
      strokeSuccessSoft: colors?.successBorder1,
      strokeSuccessSubtle: colors?.successBorder1,
      strokeWarningLoud: colors?.warningBorder2,
      strokeWarningOnloud: colors?.neutralForegroundOnBrand,
      strokeWarningSoft: colors?.warningBorder1,
      strokeWarningSubtle: colors?.warningBorder1,
      surfaceNeutralFar: colors?.neutralBackground3,
      surfaceNeutralFarther: colors?.neutralBackground5,
      surfaceNeutralNear: colors?.neutralBackground2,
      surfaceNeutralNearer: colors?.neutralBackground1,
    },
    fontFamily: {
      content: typography?.families?.primary,
      contentCode: typography?.families?.monospace,
      contentEditorial: typography?.families?.serif,
      functional: typography?.families?.primary,
    },
    fontSize: {
      contentCode: typography?.sizes?.subheader,
      contentExpressiveLarge: typography?.sizes?.heroLarge,
      contentExpressiveMedium: typography?.sizes?.hero,
      contentExpressiveSmall: typography?.sizes?.hero,
      contentH1: typography?.sizes?.hero,
      contentH2: typography?.sizes?.hero,
      contentH3: typography?.sizes?.hero,
      contentH4: typography?.sizes?.header,
      contentH5: typography?.sizes?.header,
      contentParagraphLarge: typography?.sizes?.header,
      contentParagraphMedium: typography?.sizes?.subheader,
      contentParagraphSmall: typography?.sizes?.secondary,
      contentStatement: typography?.sizes?.heroLarge,
      contentSubheadline: typography?.sizes?.subheader,
      contentSubtext: typography?.sizes?.caption,
      contentTable: typography?.sizes?.subheader,
      functionalBodyLarge: typography?.sizes?.subheader,
      functionalBodyMedium: typography?.sizes?.body,
      functionalBodySmall: typography?.sizes?.secondary,
      functionalCaption: typography?.sizes?.caption,
      functionalDisplay: typography?.sizes?.heroLarge,
      functionalPagetitle: typography?.sizes?.heroLarge,
      functionalSubtitle: typography?.sizes?.header,
      functionalTitleLarge: typography?.sizes?.hero,
      functionalTitleMedium: typography?.sizes?.hero,
      functionalTitleSmall: typography?.sizes?.header,
    },
    fontWeight: {
      contentBold: typography?.weights?.semiBold,
      contentEditorialBold: typography?.weights?.semiBold,
      contentEditorialMedium: typography?.weights?.semiBold,
      contentEditorialRegular: typography?.weights?.regular,
      contentEditorialSemibold: typography?.weights?.semiBold,
      contentMedium: typography?.weights?.semiBold,
      contentRegular: typography?.weights?.regular,
      contentSemibold: typography?.weights?.semiBold,
      functionalBold: typography?.weights?.semiBold,
      functionalMedium: typography?.weights?.semiBold,
      functionalRegular: typography?.weights?.regular,
      functionalSemibold: typography?.weights?.semiBold,
    },
    shadow: {
      high: shadows?.shadow16,
      higher: shadows?.shadow28,
      highest: shadows?.shadow64,
      low: shadows?.shadow8,
      lower: shadows?.shadow4,
      lowest: shadows?.shadow2,
    },
  });
}
