/**
 * WARNING: This file is auto-generated. Do not edit it manually.
 */

import type { FlexTokens } from '../flex.types';
import type { PartialTheme } from '../../theming/types/Theme.types';
import { omitUndefinedProperties } from './omitUndefinedProperties';

export function projectFlexToTheme(tokens: FlexTokens): PartialTheme {
  const { borderRadius, color, fontFamily, fontSize, fontWeight, shadow } = tokens;
  return omitUndefinedProperties({
    colors: {
      black: color?.fixedBlack,
      brandBackground: color?.backgroundBrandHeavy,
      brandBackground2: color?.backgroundBrandSoft,
      brandBackgroundHover: color?.hover?.backgroundBrandHeavy ?? color?.backgroundBrandHeavy,
      brandBackgroundPressed: color?.pressed?.backgroundBrandHeavy ?? color?.backgroundBrandHeavy,
      brandForeground1: color?.foregroundBrandPrimary,
      brandStroke1: color?.strokeBrandLoud,
      brandStroke2: color?.strokeBrandSubtle,
      compoundBrandBackground1: color?.backgroundBrandLoud,
      compoundBrandBackground1Hover: color?.hover?.backgroundBrandLoud ?? color?.backgroundBrandLoud,
      compoundBrandBackground1Pressed: color?.pressed?.backgroundBrandLoud ?? color?.backgroundBrandLoud,
      dangerBackground1: color?.backgroundDangerSubtle,
      dangerBackground2: color?.backgroundDangerSoft,
      dangerBackground3: color?.backgroundDangerLoud,
      dangerBorder1: color?.strokeDangerSoft,
      dangerBorder2: color?.strokeDangerLoud,
      dangerForeground1: color?.foregroundDangerPrimary,
      neutralBackground1: color?.surfaceNeutralNearer,
      neutralBackground1Hover: color?.hover?.surfaceNeutralNearer ?? color?.surfaceNeutralNearer,
      neutralBackground1Pressed: color?.pressed?.surfaceNeutralNearer ?? color?.surfaceNeutralNearer,
      neutralBackground2: color?.surfaceNeutralNear,
      neutralBackground2Hover: color?.hover?.surfaceNeutralNear ?? color?.surfaceNeutralNear,
      neutralBackground2Pressed: color?.pressed?.surfaceNeutralNear ?? color?.surfaceNeutralNear,
      neutralBackground3: color?.surfaceNeutralFar,
      neutralBackground3Hover: color?.hover?.surfaceNeutralFar ?? color?.surfaceNeutralFar,
      neutralBackground3Pressed: color?.pressed?.surfaceNeutralFar ?? color?.surfaceNeutralFar,
      neutralBackground5: color?.surfaceNeutralFarther,
      neutralBackground5Hover: color?.hover?.surfaceNeutralFarther ?? color?.surfaceNeutralFarther,
      neutralBackground5Pressed: color?.pressed?.surfaceNeutralFarther ?? color?.surfaceNeutralFarther,
      neutralBackgroundDisabled: color?.backgroundNeutralDisabled,
      neutralBackgroundInverted: color?.backgroundNeutralHeavy,
      neutralForeground1: color?.foregroundNeutralPrimary,
      neutralForeground1Hover: color?.hover?.foregroundNeutralPrimary ?? color?.foregroundNeutralPrimary,
      neutralForeground1Pressed: color?.pressed?.foregroundNeutralPrimary ?? color?.foregroundNeutralPrimary,
      neutralForeground2: color?.foregroundNeutralSecondary,
      neutralForeground2Hover: color?.hover?.foregroundNeutralSecondary ?? color?.foregroundNeutralSecondary,
      neutralForeground2Pressed: color?.pressed?.foregroundNeutralSecondary ?? color?.foregroundNeutralSecondary,
      neutralForeground3: color?.foregroundNeutralTertiary,
      neutralForeground3Hover: color?.hover?.foregroundNeutralTertiary ?? color?.foregroundNeutralTertiary,
      neutralForeground3Pressed: color?.pressed?.foregroundNeutralTertiary ?? color?.foregroundNeutralTertiary,
      neutralForegroundDisabled: color?.foregroundNeutralDisabled,
      neutralForegroundOnBrand: color?.foregroundNeutralOnloud,
      neutralForegroundOnBrandHover: color?.hover?.foregroundNeutralOnloud ?? color?.foregroundNeutralOnloud,
      neutralForegroundOnBrandPressed: color?.pressed?.foregroundNeutralOnloud ?? color?.foregroundNeutralOnloud,
      neutralStroke1: color?.strokeNeutralLoud,
      neutralStroke1Hover: color?.hover?.strokeNeutralLoud ?? color?.strokeNeutralLoud,
      neutralStroke1Pressed: color?.pressed?.strokeNeutralLoud ?? color?.strokeNeutralLoud,
      neutralStroke2: color?.strokeNeutralSubtle,
      neutralStrokeAccessible: color?.strokeNeutralHeavy,
      neutralStrokeAccessibleHover: color?.hover?.strokeNeutralHeavy ?? color?.strokeNeutralHeavy,
      neutralStrokeAccessiblePressed: color?.pressed?.strokeNeutralHeavy ?? color?.strokeNeutralHeavy,
      neutralStrokeDisabled: color?.strokeNeutralDisabled,
      strokeFocus1: color?.strokeFocusInner,
      strokeFocus2: color?.strokeFocusOuter,
      successBackground1: color?.backgroundSuccessSubtle,
      successBackground2: color?.backgroundSuccessSoft,
      successBackground3: color?.backgroundSuccessLoud,
      successBorder1: color?.strokeSuccessSoft,
      successBorder2: color?.strokeSuccessLoud,
      successForeground1: color?.foregroundSuccessPrimary,
      transparentBackground: color?.backgroundNeutralTransparent,
      transparentBackgroundHover: color?.hover?.backgroundNeutralTransparent ?? color?.backgroundNeutralTransparent,
      transparentBackgroundPressed: color?.pressed?.backgroundNeutralTransparent ?? color?.backgroundNeutralTransparent,
      transparentStroke: color?.strokeNeutralTransparent,
      transparentStrokeInteractive: color?.hover?.strokeNeutralTransparent ?? color?.strokeNeutralTransparent,
      warningBackground1: color?.backgroundWarningSubtle,
      warningBackground2: color?.backgroundWarningSoft,
      warningBackground3: color?.backgroundWarningLoud,
      warningBorder1: color?.strokeWarningSoft,
      warningBorder2: color?.strokeWarningLoud,
      warningForeground1: color?.foregroundWarningPrimary,
      white: color?.fixedWhite,
    },
    components: {
      Button: {
        tokens: {
          borderRadius: borderRadius?.base200,
        },
      },
    },
    shadows: {
      shadow16: shadow?.high,
      shadow2: shadow?.lowest,
      shadow28: shadow?.higher,
      shadow4: shadow?.lower,
      shadow64: shadow?.highest,
      shadow8: shadow?.low,
    },
    typography: {
      families: {
        monospace: fontFamily?.contentCode,
        primary: fontFamily?.functional,
        serif: fontFamily?.contentEditorial,
      },
      sizes: {
        body: fontSize?.functionalBodyMedium,
        caption: fontSize?.functionalCaption,
        header: fontSize?.functionalSubtitle,
        hero: fontSize?.functionalTitleMedium,
        heroLarge: fontSize?.functionalPagetitle,
        secondary: fontSize?.functionalBodySmall,
        subheader: fontSize?.functionalBodyLarge,
      },
      weights: {
        regular: fontWeight?.functionalRegular,
        semiBold: fontWeight?.functionalSemibold,
      },
    },
  }) as PartialTheme;
}
