/**
 * Generated spec emitter.
 *
 * Inline plans are compiled into a single host-side WebdriverIO spec with one tagged Mocha test
 * per story. The generated file imports the manifest and the plan runner; it never contains
 * code derived from story content, so a malformed plan can only fail validation, never execute.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

import { isInlinePlan } from '../story-plan.ts';
import type { StoryTestManifest } from '../types.ts';

export interface EmitGeneratedSpecOptions {
  manifest: StoryTestManifest;
  /** Absolute path of the spec to write. */
  outputPath: string;
  /** Absolute path of the manifest JSON the spec loads at runtime. */
  manifestPath: string;
  /** Module specifier used for the desktop-driver imports. */
  packageSpecifier?: string;
}

/** Writes the manifest JSON and the compiled inline-plan spec. */
export function emitGeneratedStorySpec(options: EmitGeneratedSpecOptions): { specPath: string; manifestPath: string } {
  const packageSpecifier = options.packageSpecifier ?? '@fluentui-react-native/desktop-driver';
  const inlineEntries = options.manifest.entries.filter((entry) => isInlinePlan(entry.plan));

  fs.mkdirSync(path.dirname(options.manifestPath), { recursive: true });
  fs.writeFileSync(options.manifestPath, `${JSON.stringify(options.manifest, null, 2)}\n`, 'utf8');

  const relativeManifest = toModuleSpecifier(path.dirname(options.outputPath), options.manifestPath);

  const body = inlineEntries
    .map((entry) => {
      const literal = JSON.stringify(entry.storyId);
      return [
        `describe(${JSON.stringify(`${entry.tag} ${entry.title} / ${entry.name}`)}, () => {`,
        `  it(${JSON.stringify(`runs the ${entry.plan.id} plan`)}, async () => {`,
        `    const entry = manifest.entries.find((candidate) => candidate.storyId === ${literal});`,
        `    if (!entry) {`,
        `      throw new Error(${JSON.stringify(`Story ${entry.storyId} is missing from the generated desktop test manifest`)});`,
        `    }`,
        `    await browser.desktop.selectStory(${literal});`,
        `    await runInlineStoryPlan(entry.plan as InlineStoryPlan, { browser });`,
        `  });`,
        `});`,
      ].join('\n');
    })
    .join('\n\n');

  const contents = [
    '// Generated by @fluentui-react-native/desktop-driver. Do not edit.',
    '//',
    '// One tagged Mocha test per story with an inline `parameters.desktopTest` plan. Regenerate',
    '// with `desktop-driver stories generate`.',
    `import manifest from ${JSON.stringify(relativeManifest)} with { type: 'json' };`,
    `import type { InlineStoryPlan } from ${JSON.stringify(packageSpecifier)};`,
    `import { runInlineStoryPlan } from ${JSON.stringify(`${packageSpecifier}/wdio`)};`,
    '',
    body.length > 0
      ? body
      : "describe('[story:none] no inline desktop story plans', () => {\n  it('has nothing to run', () => undefined);\n});",
    '',
  ].join('\n');

  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, contents, 'utf8');

  return { specPath: options.outputPath, manifestPath: options.manifestPath };
}

function toModuleSpecifier(fromDirectory: string, target: string): string {
  const relative = path.relative(fromDirectory, target).split(path.sep).join('/');
  return relative.startsWith('.') ? relative : `./${relative}`;
}

/**
 * Discovery check.
 *
 * Generation fails when a linked spec does not contain the story's tag, so a mistyped suite title
 * is caught at build time instead of silently running zero tests.
 */
export function verifyLinkedSpecTags(manifest: StoryTestManifest): readonly string[] {
  const problems: string[] = [];
  for (const entry of manifest.entries) {
    if (isInlinePlan(entry.plan)) {
      continue;
    }
    let contents: string;
    try {
      contents = fs.readFileSync(entry.spec, 'utf8');
    } catch (error) {
      problems.push(`${entry.storyId}: cannot read ${entry.spec} (${(error as Error).message})`);
      continue;
    }
    if (!contents.includes(entry.tag)) {
      problems.push(`${entry.storyId}: ${entry.spec} does not contain the required suite tag ${entry.tag}`);
    }
  }
  return problems;
}
