/**
 * Generated spec emitter.
 *
 * Inline plans are compiled into a single host-side WebdriverIO spec with one tagged Mocha test
 * per story. The generated file imports the manifest and the plan runner; it never contains
 * code derived from story content, so a malformed plan can only fail validation, never execute.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

import { parse } from '@babel/parser';

import { isInlinePlan } from '../story-plan.ts';
import { DesktopValidationError } from '../errors.ts';
import type { StoryTestManifest } from '../types.ts';

export interface EmitGeneratedSpecOptions {
  manifest: StoryTestManifest;
  /** Absolute path of the spec to write. */
  outputPath: string;
  /** Absolute path of the manifest JSON the spec loads at runtime. */
  manifestPath: string;
  /** Module specifier used for the desktop-driver imports. */
  packageSpecifier?: string;
}

/** Writes the manifest JSON and the compiled inline-plan spec. */
export function emitGeneratedStorySpec(options: EmitGeneratedSpecOptions): { specPath: string; manifestPath: string } {
  const packageSpecifier = options.packageSpecifier ?? '@fluentui-react-native/desktop-driver';
  const inlineEntries = options.manifest.entries.filter((entry) => isInlinePlan(entry.plan));

  const relativeManifest = toModuleSpecifier(path.dirname(options.outputPath), options.manifestPath);

  const body = inlineEntries
    .map((entry) => {
      const literal = JSON.stringify(entry.storyId);
      return [
        `describe(${JSON.stringify(`${entry.tag} ${entry.title} / ${entry.name}`)}, () => {`,
        `  it(${JSON.stringify(`runs the ${entry.plan.id} plan`)}, async () => {`,
        `    const entry = manifest.entries.find((candidate) => candidate.storyId === ${literal});`,
        `    if (!entry) {`,
        `      throw new Error(${JSON.stringify(`Story ${entry.storyId} is missing from the generated desktop test manifest`)});`,
        `    }`,
        `    await browser.desktop.selectStory(${literal});`,
        `    await runInlineStoryPlan(entry.plan as InlineStoryPlan, { browser });`,
        `  });`,
        `});`,
      ].join('\n');
    })
    .join('\n\n');

  const contents = [
    '// Generated by @fluentui-react-native/desktop-driver. Do not edit.',
    '//',
    '// One tagged Mocha test per story with an inline `parameters.desktopTest` plan. Regenerate',
    '// with `desktop-driver stories generate`.',
    `import manifest from ${JSON.stringify(relativeManifest)} with { type: 'json' };`,
    `import type { InlineStoryPlan } from ${JSON.stringify(packageSpecifier)};`,
    `import { runInlineStoryPlan } from ${JSON.stringify(`${packageSpecifier}/wdio`)};`,
    '',
    body,
    '',
  ].join('\n');

  fs.mkdirSync(path.dirname(options.manifestPath), { recursive: true });
  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  const nonce = `${process.pid}-${Date.now()}`;
  const manifestTemporary = `${options.manifestPath}.${nonce}.tmp`;
  const specTemporary = `${options.outputPath}.${nonce}.tmp`;
  try {
    fs.writeFileSync(manifestTemporary, `${JSON.stringify(options.manifest, null, 2)}\n`, 'utf8');
    fs.writeFileSync(specTemporary, contents, 'utf8');
    // The manifest is the commit marker: a consumer cannot observe it until the matching spec is
    // already in place.
    fs.renameSync(specTemporary, options.outputPath);
    fs.renameSync(manifestTemporary, options.manifestPath);
  } catch (error) {
    for (const temporary of [manifestTemporary, specTemporary]) {
      try {
        fs.unlinkSync(temporary);
      } catch {
        // The file may already have been renamed or never created.
      }
    }
    throw error;
  }

  return { specPath: options.outputPath, manifestPath: options.manifestPath };
}

function toModuleSpecifier(fromDirectory: string, target: string): string {
  const relative = path.relative(fromDirectory, target).split(path.sep).join('/');
  return relative.startsWith('.') ? relative : `./${relative}`;
}

/**
 * Discovery check.
 *
 * Generation fails when a linked spec does not contain the story's tag, so a mistyped suite title
 * is caught at build time instead of silently running zero tests.
 */
export function verifyLinkedSpecTags(manifest: StoryTestManifest): readonly string[] {
  const problems: string[] = [];
  for (const entry of manifest.entries) {
    if (isInlinePlan(entry.plan)) {
      continue;
    }
    let contents: string;
    try {
      contents = fs.readFileSync(entry.spec, 'utf8');
    } catch (error) {
      problems.push(`${entry.storyId}: cannot read ${entry.spec} (${(error as Error).message})`);
      continue;
    }
    if (!hasExecutableTaggedTest(contents, entry.tag, entry.spec)) {
      problems.push(`${entry.storyId}: ${entry.spec} does not declare a runnable suite with the required tag ${entry.tag}`);
    }
  }
  return problems;
}

/* eslint-disable @typescript-eslint/no-explicit-any -- Babel nodes are traversed structurally */
function hasExecutableTaggedTest(contents: string, tag: string, file: string): boolean {
  let ast: any;
  try {
    ast = parse(contents, { sourceType: 'module', plugins: ['typescript', 'jsx'], errorRecovery: false });
  } catch (error) {
    throw new DesktopValidationError(`Failed to parse linked desktop spec ${file}`, [(error as Error).message]);
  }

  const calleeName = (callee: any): { name?: string; skipped: boolean } => {
    if (callee?.type === 'Identifier') {
      return { name: callee.name, skipped: false };
    }
    if (callee?.type === 'MemberExpression' && !callee.computed && callee.object?.type === 'Identifier') {
      return { name: callee.object.name, skipped: callee.property?.name === 'skip' || callee.property?.name === 'todo' };
    }
    return { skipped: false };
  };
  const stringValue = (node: any): string | undefined =>
    node?.type === 'StringLiteral'
      ? node.value
      : node?.type === 'TemplateLiteral' && node.expressions.length === 0
        ? node.quasis[0]?.value.raw
        : undefined;
  const containsRunnableTest = (node: any, skippedAncestor = false): boolean => {
    if (!node || typeof node !== 'object') {
      return false;
    }
    if (node.type === 'CallExpression') {
      const callee = calleeName(node.callee);
      if (['describe', 'context', 'suite'].includes(callee.name ?? '')) {
        return node.arguments.slice(1).some((child: any) => containsRunnableTest(child, skippedAncestor || callee.skipped));
      }
      if (!callee.skipped && ['it', 'test', 'specify'].includes(callee.name ?? '')) {
        return !skippedAncestor;
      }
    }
    return Object.values(node).some((child) =>
      Array.isArray(child)
        ? child.some((candidate) => containsRunnableTest(candidate, skippedAncestor))
        : containsRunnableTest(child, skippedAncestor),
    );
  };
  const findTaggedSuite = (node: any): boolean => {
    if (!node || typeof node !== 'object') {
      return false;
    }
    if (node.type === 'CallExpression') {
      const callee = calleeName(node.callee);
      const title = stringValue(node.arguments?.[0]);
      if (!callee.skipped && ['describe', 'context', 'suite'].includes(callee.name ?? '') && title?.includes(tag)) {
        return node.arguments.slice(1).some(containsRunnableTest);
      }
    }
    return Object.values(node).some((child) => (Array.isArray(child) ? child.some(findTaggedSuite) : findTaggedSuite(child)));
  };
  return findTaggedSuite(ast.program);
}
/* eslint-enable @typescript-eslint/no-explicit-any */
