jobs:
  - job: E2E_UWP_TEST
    displayName: E2E UWP Testing
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    pool:
      vmImage: "windows-2019"

    steps:
      - checkout: self
        persistCredentials: true

      #
      # Downloading Secure Files
      #
      - task: DownloadSecureFile@1
        name: UwpCertificate
        displayName: "Download UWP App Certificate"
        inputs:
          secureFile: "FluentTester_TemporaryKey.pfx"

      - task: DownloadSecureFile@1
        name: AzureCredentials
        displayName: "Download Nuget Credential Provider"
        inputs:
          secureFile: "installcredprovider.ps1"

      - task: DownloadSecureFile@1
        name: Windows10Sdk
        displayName: "Download Windows 10 SDK"
        inputs:
          secureFile: "Install-WindowsSDKISO.ps1"

      #
      # Downloading Programs
      #
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"

      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: "5.6.0"
        displayName: "Install Nuget"

      - template: install-SDK.yml
        parameters:
          sdkVersion: $(Win10Version)
          filePath: $(Windows10Sdk.secureFilePath)

      - task: PowerShell@2
        inputs:
          filePath: $(AzureCredentials.secureFilePath)
          arguments: "-AddNetfx"
        displayName: "Install Azure Credentials Plugin for NuGet"

      - task: PowerShell@2
        inputs:
          filePath: $(AzureCredentials.secureFilePath)
          arguments: "-AddNetfx"
        displayName: "Install Azure Credentials Plugin for NuGet"

      - task: CmdLine@2
        displayName: Validating Azure Credentials in Correct Location
        inputs:
          script: dir C:\Users\VssAdministrator\.nuget\plugins

      - template: setup-repo.yml

      # - task: NuGetCommand@2
      #   displayName: NuGet restore - FluentTester
      #   inputs:
      #     command: restore
      #     noCache: true
      #     restoreSolution: apps/windows/windows/FluentTester.sln
      #     verbosityRestore: Detailed # Options: quiet, normal, detailed
      - script: yarn windows
        displayName: Running UWP App
        workingDirectory: apps/windows
      # Wait for app to launch. A workaround to avoid WinAppDriver error: Failed to locate opened application window with appId
      - task: PowerShell@2
        displayName: Wait for app to launch
        inputs:
          targetType: inline # filePath | inline
          script: |
            Start-Sleep -Seconds 30
      - script: yarn e2etest
        displayName: Running UWP E2E Tests
        workingDirectory: apps/windows
