jobs:
  - job: E2E_UWP_TEST
    displayName: E2E UWP Testing
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    pool:
      vmImage: "windows-2019"

    steps:
      - checkout: self
        persistCredentials: true

      # Download Node.JS
      - task: NodeTool@0
        inputs:
          versionSpec: "12.16.1"
        displayName: "Install Node"

      # Download Nuget
      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: "5.6.0"
        displayName: "Install Nuget"

      # Download App Certificate
      - task: DownloadSecureFile@1
        name: UwpCertificate
        displayName: "Download UWP App Certificate"
        inputs:
          secureFile: "FluentTester_TemporaryKey.pfx"

      # Add certificate to store
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: certutil –f –p password –importpfx $(UwpCertificate.secureFilePath)
        displayName: "Add Certificate to Personal Store"

      # Download Azure Credentials Plugin
      - task: DownloadSecureFile@1
        name: AzureCredentials
        displayName: "Download Nuget Credential Provider"
        inputs:
          secureFile: "installcredprovider.ps1"

      # Install Azure Credentials Plugin
      - task: PowerShell@2
        inputs:
          filePath: $(AzureCredentials.secureFilePath)
          arguments: "-AddNetfx -Force"
        displayName: "Install Azure Credentials Plugin for NuGet"

      - template: setup-repo.yml

      # Run server + FluentTester App
      - script: |
          yarn windows
        workingDirectory: apps\windows
        displayName: Run FluentTester App

      # Wait for app to launch. A workaround to avoid WinAppDriver error: Failed to locate opened application window with appId
      - task: PowerShell@2
        displayName: Wait for app to launch
        inputs:
          targetType: inline # filePath | inline
          script: |
            Start-Sleep -Seconds 60

      # Kill FluentTester, leave server up and running
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: Stop-Process -Name FluentTester
        displayName: Kill FluentTester Process

      - script: |
          yarn e2etest
        workingDirectory: apps\windows
        displayName: Running E2E Test
