jobs:
  - job: E2E_UWP_TEST
    displayName: E2E UWP Testing
    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    pool:
      vmImage: "windows-2019"

    steps:
      - checkout: self
        persistCredentials: true

      - task: DownloadSecureFile@1
        name: UwpCertificate
        inputs:
          secureFile: FluentTester_TemporaryKey.pfx
        displayName: "Download UWP App Certificate"

      - powershell: certutil –f –p password –importpfx $(UwpCertificate.secureFilePath)
        displayName: "Add Certificate to Personal Store"

      - task: DownloadSecureFile@1
        name: AzureCredentials
        inputs:
          secureFile: "installcredprovider.ps1"
        displayName: "Download Azure Credentials Plugin for NuGet"

      - task: PowerShell@2
        inputs:
          filePath: $(AzureCredentials.secureFilePath)
          arguments: "-AddNetfx -Force"
        displayName: "Install Azure Credentials Plugin for NuGet"

      - script: yarn windows
        workingDirectory: apps\windows
        displayName: "Run FluentTester App"

      # Wait for app to launch. A workaround to avoid WinAppDriver error: Failed to locate opened application window with appId
      - powershell: Start-Sleep -Seconds 60
        displayName: "Wait for app to launch"

      # Kill FluentTester, leave server up and running
      - powershell: Stop-Process -Name FluentTester
        displayName: "Kill FluentTester Process"

      - script: yarn e2etest
        workingDirectory: apps\windows
        displayName: "UWP E2E Testing"
