require_relative '../../../node_modules/react-native-test-app/macos/test_app.rb'

workspace 'FluentUITester.xcworkspace'

use_test_app! do |target|
  target.app do
  end

  target.tests do
  end

  target.ui_tests do
  end
end
