/**
 * Token-name metadata.
 *
 * Reachable only via the `./metadata` subpath export (see package.json) —
 * deliberately NOT re-exported from `./index.ts`. The package root ships
 * types only, so consumers importing types still pay zero runtime cost;
 * tooling that needs to enumerate every theme token (an analyzer
 * building a sentinel test theme, a documentation generator, etc.)
 * imports `'@fluentui-react-native/theme-types/metadata'` and gets these
 * tuples without polluting the type-only surface.
 *
 * If you add or remove a key in `Color.types.ts`, `Typography.types.ts`,
 * `Shadow.types.ts`, or `Theme.types.ts`, update the corresponding tuple
 * here. Drift is caught by the parity tests in
 * `src/__tests__/metadata.test.ts` — they fail at `tsgo` time when the
 * tuple no longer matches the interface.
 */

// ----- Color -----------------------------------------------------------------------------------

// Grouped to mirror the four interfaces that compose `Palette`. The
// per-group tuples aren't exported individually because callers should
// treat colors as one flat namespace — the grouping is just for human
// readability when this file is edited.

const PALETTE_TEXT_COLOR_NAMES = [
  'bodyText',
  'bodyTextChecked',
  'subText',
  'actionLink',
  'link',
  'linkHovered',
  'linkPressed',
  'disabledText',
  'disabledBodyText',
  'errorText',
  'inputText',
  'inputPlaceholderText',
  'buttonText',
  'buttonTextHovered',
  'buttonTextChecked',
  'buttonTextPressed',
  'buttonTextDisabled',
  'primaryButtonText',
  'primaryButtonTextHovered',
  'primaryButtonTextPressed',
  'primaryButtonTextDisabled',
] as const;

const PALETTE_BACKGROUND_COLOR_NAMES = [
  'background',
  'bodyStandoutBackground',
  'bodyFrameBackground',
  'bodyFrameDivider',
  'bodyDivider',
  'disabledBackground',
  'focusBorder',
  'variantBorder',
  'inputBorder',
  'inputBackground',
  'inputFocusBorderAlt',
  'buttonBackground',
  'buttonBackgroundChecked',
  'buttonBackgroundHovered',
  'buttonBackgroundDisabled',
  'buttonBackgroundPressed',
  'buttonBorder',
  'buttonBorderFocused',
  'buttonBorderDisabled',
  'primaryButtonBackground',
  'primaryButtonBackgroundHovered',
  'primaryButtonBackgroundPressed',
  'primaryButtonBackgroundDisabled',
  'primaryButtonBorder',
  'primaryButtonBorderFocused',
  'accentButtonBackground',
  'menuBackground',
  'menuDivider',
  'menuIcon',
  'menuItemBackgroundHovered',
  'menuItemBackgroundPressed',
  'menuItemText',
  'menuItemTextHovered',
  'listHeaderBackgroundHovered',
  'listHeaderBackgroundPressed',
] as const;

const CONTROL_COLOR_TOKEN_NAMES = [
  'defaultBackground',
  'defaultBorder',
  'defaultContent',
  'defaultIcon',
  'defaultHoveredBackground',
  'defaultHoveredBorder',
  'defaultHoveredContent',
  'defaultHoveredIcon',
  'defaultFocusedBackground',
  'defaultFocusedBorder',
  'defaultFocusedContent',
  'defaultFocusedIcon',
  'defaultPressedBackground',
  'defaultPressedBorder',
  'defaultPressedContent',
  'defaultPressedIcon',
  'defaultDisabledBackground',
  'defaultDisabledBorder',
  'defaultDisabledContent',
  'defaultDisabledIcon',
  'ghostBackground',
  'ghostBorder',
  'ghostContent',
  'ghostIcon',
  'ghostHoveredBackground',
  'ghostHoveredBorder',
  'ghostHoveredContent',
  'ghostHoveredIcon',
  'ghostFocusedBackground',
  'ghostFocusedBorder',
  'ghostFocusedContent',
  'ghostFocusedIcon',
  'ghostPressedBackground',
  'ghostPressedBorder',
  'ghostPressedContent',
  'ghostPressedIcon',
  'ghostDisabledBackground',
  'ghostDisabledBorder',
  'ghostDisabledContent',
  'ghostDisabledIcon',
  'brandedBackground',
  'brandedDisabledBorder',
  'brandedSecondaryContent',
  'brandedFocusedSecondaryContent',
  'brandedHoveredSecondaryContent',
  'brandedPressedSecondaryContent',
  'defaultCheckedBackground',
  'defaultCheckedContent',
  'defaultCheckedHoveredBackground',
  'defaultCheckedHoveredContent',
  'ghostCheckedBackground',
  'ghostCheckedContent',
  'ghostCheckedHoveredBackground',
  'ghostCheckedHoveredContent',
  'ghostCheckedHoveredBorder',
  'ghostSecondaryContent',
  'ghostFocusedSecondaryContent',
  'ghostHoveredSecondaryContent',
  'ghostPressedSecondaryContent',
  'defaultHoveredSecondaryContent',
  'defaultPressedSecondaryContent',
  'checkboxBackground',
  'checkboxBackgroundDisabled',
  'checkmarkColor',
  'checkboxBorderColor',
  'personaActivityRing',
  'personaActivityGlow',
] as const;

const ALIAS_COLOR_TOKEN_NAMES = [
  'neutralForeground1',
  'neutralForeground1Hover',
  'neutralForeground1Pressed',
  'neutralForeground1Selected',
  'neutralForeground2',
  'neutralForeground2Hover',
  'neutralForeground2Pressed',
  'neutralForeground2Selected',
  'neutralForeground2BrandHover',
  'neutralForeground2BrandPressed',
  'neutralForeground2BrandSelected',
  'neutralForeground3',
  'neutralForeground3Hover',
  'neutralForeground3Pressed',
  'neutralForeground3Selected',
  'neutralForeground3BrandHover',
  'neutralForeground3BrandPressed',
  'neutralForeground3BrandSelected',
  'neutralForeground4',
  'neutralForegroundDisabled',
  'neutralForegroundDisabled1',
  'neutralForegroundDisabled2',
  'neutralForegroundOnColor',
  'neutralForegroundDarkStatic',
  'neutralForegroundLightStatic',
  'neutralForegroundOnBrand',
  'neutralForegroundOnBrandHover',
  'neutralForegroundOnBrandPressed',
  'neutralForegroundOnBrandSelected',
  'neutralForegroundInverted',
  'neutralForegroundInvertedLink',
  'neutralForegroundInvertedLinkHover',
  'neutralForegroundInvertedLinkPressed',
  'neutralForegroundInvertedLinkSelected',
  'brandForegroundLink',
  'brandForegroundLinkHover',
  'brandForegroundLinkPressed',
  'brandForegroundLinkSelected',
  'compoundBrandForeground1',
  'compoundBrandForeground1Hover',
  'compoundBrandForeground1Pressed',
  'brandForeground1',
  'brandForeground1Pressed',
  'brandForeground1Selected',
  'brandForeground2',
  'brandForegroundTint',
  'brandForeground1Disabled',
  'brandForegroundDisabled1',
  'brandForegroundDisabled2',
  'neutralBackground1',
  'neutralBackground1Hover',
  'neutralBackground1Pressed',
  'neutralBackground1Selected',
  'neutralBackground2',
  'neutralBackground2Hover',
  'neutralBackground2Pressed',
  'neutralBackground2Selected',
  'neutralBackground3',
  'neutralBackground3Hover',
  'neutralBackground3Pressed',
  'neutralBackground3Selected',
  'neutralBackground4',
  'neutralBackground4Hover',
  'neutralBackground4Pressed',
  'neutralBackground4Selected',
  'neutralBackground5',
  'neutralBackground5Hover',
  'neutralBackground5Pressed',
  'neutralBackground5Selected',
  'neutralBackground6',
  'neutralBackgroundCanvas',
  'neutralBackgroundDarkStatic',
  'neutralBackgroundInverted',
  'neutralBackgroundDisabled',
  'neutralBackgroundLightStatic',
  'neutralBackgroundLightStaticDisabled',
  'subtleBackground',
  'subtleBackgroundHover',
  'subtleBackgroundPressed',
  'subtleBackgroundSelected',
  'transparentBackground',
  'transparentBackgroundHover',
  'transparentBackgroundPressed',
  'transparentBackgroundSelected',
  'brandBackground',
  'brandBackgroundHover',
  'brandBackgroundPressed',
  'brandBackgroundDisabled',
  'brandBackgroundSelected',
  'compoundBrandBackground1',
  'compoundBrandBackground1Hover',
  'compoundBrandBackground1Pressed',
  'brandBackgroundStatic',
  'brandBackground2',
  'brandBackground2Pressed',
  'brandBackground2Selected',
  'brandBackground3',
  'brandBackgroundTint',
  'brandBackgroundInverted',
  'brandBackgroundInvertedDisabled',
  'neutralStencil1',
  'neutralStencil2',
  'neutralStrokeAccessible',
  'neutralStrokeAccessibleHover',
  'neutralStrokeAccessiblePressed',
  'neutralStrokeAccessibleSelected',
  'neutralStroke1',
  'neutralStroke1Hover',
  'neutralStroke1Pressed',
  'neutralStroke1Selected',
  'neutralStroke2',
  'neutralStroke3',
  'neutralStrokeDisabled',
  'neutralStrokeFocus1',
  'neutralStrokeFocus2',
  'strokeFocus1',
  'strokeFocus2',
  'brandStroke1',
  'brandStroke1Pressed',
  'brandStroke1Selected',
  'brandStroke2',
  'brandStrokeTint',
  'compoundBrandStroke1',
  'compoundBrandStroke1Hover',
  'compoundBrandStroke1Pressed',
  'transparentStroke',
  'transparentStrokeInteractive',
  'transparentStrokeDisabled',
  'redBackground1',
  'redBackground2',
  'redBackground3',
  'redForeground1',
  'redForeground2',
  'redForeground3',
  'redBorderActive',
  'redBorder1',
  'redBorder2',
  'dangerBackground1',
  'dangerBackground2',
  'dangerBackground3',
  'dangerForeground1',
  'dangerForeground2',
  'dangerForeground3',
  'dangerForegroundInverted',
  'dangerBorderActive',
  'dangerBorder1',
  'dangerBorder2',
  'dangerStroke1',
  'successBackground1',
  'successBackground2',
  'successBackground3',
  'successForeground1',
  'successForeground2',
  'successForeground3',
  'successForegroundInverted',
  'successBorderActive',
  'successBorder1',
  'successBorder2',
  'successStroke1',
  'warningBackground1',
  'warningBackground2',
  'warningBackground3',
  'warningForeground1',
  'warningForeground2',
  'warningForeground3',
  'warningForegroundInverted',
  'warningBorderActive',
  'warningBorder1',
  'warningBorder2',
  'warningStroke1',
  'severeBackground1',
  'severeBackground2',
  'severeBackground3',
  'severeForeground1',
  'severeForeground2',
  'severeForeground3',
  'severeBorderActive',
  'severeBorder1',
  'severeBorder2',
  'severeStroke1',
  'outofofficeBackground1',
  'outofofficeBackground2',
  'outofofficeBackground3',
  'outofofficeForeground1',
  'outofofficeForeground2',
  'outofofficeForeground3',
  'outofofficeBorderActive',
  'outofofficeBorder1',
  'outofofficeBorder2',
  'presenceAway',
  'presenceDnd',
  'presenceAvailable',
  'presenceOof',
] as const;

/**
 * Every named color key reachable through `Theme['colors']`. The
 * underlying `ThemeColorDefinition` has an open index signature
 * (`[customColor: string]: ColorValue`), so this tuple enumerates the
 * statically-declared keys only — that's the surface that matters for
 * code generation and analyzer coverage.
 *
 * The order here mirrors the source interfaces (text → background →
 * control → alias) so a key's neighbors tell you which interface owns it.
 */
export const COLOR_TOKEN_NAMES = [
  ...PALETTE_TEXT_COLOR_NAMES,
  ...PALETTE_BACKGROUND_COLOR_NAMES,
  ...CONTROL_COLOR_TOKEN_NAMES,
  ...ALIAS_COLOR_TOKEN_NAMES,
] as const;

export type ColorTokenName = (typeof COLOR_TOKEN_NAMES)[number];

// ----- Spacing --------------------------------------------------------------------------------

export const SPACING_TOKEN_NAMES = ['s2', 's1', 'm', 'l1', 'l2'] as const;
export type SpacingTokenName = (typeof SPACING_TOKEN_NAMES)[number];

// ----- Shadow ---------------------------------------------------------------------------------

export const SHADOW_TOKEN_NAMES = [
  'shadow2',
  'shadow4',
  'shadow8',
  'shadow16',
  'shadow28',
  'shadow64',
  'shadow2brand',
  'shadow4brand',
  'shadow8brand',
  'shadow16brand',
  'shadow28brand',
  'shadow64brand',
] as const;
export type ShadowTokenName = (typeof SHADOW_TOKEN_NAMES)[number];

// ----- Typography -----------------------------------------------------------------------------

export const TYPOGRAPHY_FAMILY_NAMES = [
  'primary',
  'secondary',
  'cursive',
  'monospace',
  'numeric',
  'sansSerif',
  'serif',
] as const;
export type TypographyFamilyName = (typeof TYPOGRAPHY_FAMILY_NAMES)[number];

export const TYPOGRAPHY_SIZE_NAMES = [
  'caption',
  'secondary',
  'body',
  'subheader',
  'header',
  'hero',
  'heroLarge',
] as const;
export type TypographySizeName = (typeof TYPOGRAPHY_SIZE_NAMES)[number];

export const TYPOGRAPHY_WEIGHT_NAMES = ['regular', 'semiBold'] as const;
export type TypographyWeightName = (typeof TYPOGRAPHY_WEIGHT_NAMES)[number];

// `Variants` interleaves a required v1 set and an optional v2 set in one
// interface. Splitting the tuples preserves that distinction so callers
// that only care about the v1 surface (e.g., legacy components) can opt
// out of v2 ramps without an Exclude<> dance.
const TYPOGRAPHY_V1_VARIANT_NAMES = [
  'captionStandard',
  'secondaryStandard',
  'secondarySemibold',
  'bodyStandard',
  'bodySemibold',
  'subheaderStandard',
  'subheaderSemibold',
  'headerStandard',
  'headerSemibold',
  'heroStandard',
  'heroSemibold',
  'heroLargeStandard',
  'heroLargeSemibold',
] as const;

const TYPOGRAPHY_V2_VARIANT_NAMES = [
  'caption1',
  'caption1Strong',
  'caption2',
  'body1',
  'body1Strong',
  'body2',
  'body2Strong',
  'subtitle1',
  'subtitle1Strong',
  'subtitle2',
  'subtitle2Strong',
  'title1',
  'title1Strong',
  'title2',
  'title3',
  'largeTitle',
  'display',
] as const;

export const TYPOGRAPHY_VARIANT_NAMES = [
  ...TYPOGRAPHY_V1_VARIANT_NAMES,
  ...TYPOGRAPHY_V2_VARIANT_NAMES,
] as const;

export type TypographyVariantName = (typeof TYPOGRAPHY_VARIANT_NAMES)[number];
