// This file was generated by 'update-profile.js'
/* eslint-disable */
module.exports = {
  "0.72": {
    "@fluentui-react-native/e2e-testing": {
      "name": "@fluentui-react-native/e2e-testing",
      "version": "1.34.9"
    },
    "@fluentui-react-native/tester": {
      "name": "@fluentui-react-native/tester",
      "version": "0.167.2"
    },
    "@fluentui-react-native/tester-win32": {
      "name": "@fluentui-react-native/tester-win32",
      "version": "0.37.32"
    },
    "@fluentui-react-native/avatar": {
      "name": "@fluentui-react-native/avatar",
      "version": "1.11.8"
    },
    "@fluentui-react-native/badge": {
      "name": "@fluentui-react-native/badge",
      "version": "0.8.8"
    },
    "@fluentui-react-native/button": {
      "name": "@fluentui-react-native/button",
      "version": "0.36.10"
    },
    "@fluentui-react-native/callout": {
      "name": "@fluentui-react-native/callout",
      "version": "0.25.7"
    },
    "@fluentui-react-native/checkbox": {
      "name": "@fluentui-react-native/checkbox",
      "version": "0.22.7"
    },
    "@fluentui-react-native/chip": {
      "name": "@fluentui-react-native/chip",
      "version": "0.3.8"
    },
    "@fluentui-react-native/contextual-menu": {
      "name": "@fluentui-react-native/contextual-menu",
      "version": "0.23.10"
    },
    "@fluentui-react-native/divider": {
      "name": "@fluentui-react-native/divider",
      "version": "0.6.8"
    },
    "@fluentui-react-native/focus-trap-zone": {
      "name": "@fluentui-react-native/focus-trap-zone",
      "version": "0.11.7"
    },
    "@fluentui-react-native/focus-zone": {
      "name": "@fluentui-react-native/focus-zone",
      "version": "0.16.7"
    },
    "@fluentui-react-native/icon": {
      "name": "@fluentui-react-native/icon",
      "version": "0.20.8"
    },
    "@fluentui-react-native/input": {
      "name": "@fluentui-react-native/input",
      "version": "0.5.8"
    },
    "@fluentui-react-native/link": {
      "name": "@fluentui-react-native/link",
      "version": "0.21.7"
    },
    "@fluentui-react-native/menu": {
      "name": "@fluentui-react-native/menu",
      "version": "1.12.12"
    },
    "@fluentui-react-native/menu-button": {
      "name": "@fluentui-react-native/menu-button",
      "version": "0.12.12"
    },
    "@fluentui-react-native/notification": {
      "name": "@fluentui-react-native/notification",
      "version": "0.24.10"
    },
    "@fluentui-react-native/persona": {
      "name": "@fluentui-react-native/persona",
      "version": "0.15.7"
    },
    "@fluentui-react-native/persona-coin": {
      "name": "@fluentui-react-native/persona-coin",
      "version": "0.14.7"
    },
    "@fluentui-react-native/pressable": {
      "name": "@fluentui-react-native/pressable",
      "version": "0.11.7"
    },
    "@fluentui-react-native/radio-group": {
      "name": "@fluentui-react-native/radio-group",
      "version": "0.20.9"
    },
    "@fluentui-react-native/separator": {
      "name": "@fluentui-react-native/separator",
      "version": "0.17.7"
    },
    "@fluentui-react-native/stack": {
      "name": "@fluentui-react-native/stack",
      "version": "0.9.7"
    },
    "@fluentui-react-native/switch": {
      "name": "@fluentui-react-native/switch",
      "version": "0.12.7"
    },
    "@fluentui-react-native/tablist": {
      "name": "@fluentui-react-native/tablist",
      "version": "0.5.14"
    },
    "@fluentui-react-native/text": {
      "name": "@fluentui-react-native/text",
      "version": "0.22.7"
    },
    "@uifabricshared/foundation-composable": {
      "name": "@uifabricshared/foundation-composable",
      "version": "0.12.3"
    },
    "@uifabricshared/foundation-compose": {
      "name": "@uifabricshared/foundation-compose",
      "version": "1.14.20"
    },
    "@uifabricshared/foundation-settings": {
      "name": "@uifabricshared/foundation-settings",
      "version": "0.14.0"
    },
    "@uifabricshared/foundation-tokens": {
      "name": "@uifabricshared/foundation-tokens",
      "version": "0.14.5"
    },
    "@uifabricshared/theme-registry": {
      "name": "@uifabricshared/theme-registry",
      "version": "0.11.0"
    },
    "@uifabricshared/themed-settings": {
      "name": "@uifabricshared/themed-settings",
      "version": "0.11.0"
    },
    "@uifabricshared/theming-ramp": {
      "name": "@uifabricshared/theming-ramp",
      "version": "0.19.10"
    },
    "@uifabricshared/theming-react-native": {
      "name": "@uifabricshared/theming-react-native",
      "version": "0.19.7"
    },
    "@fluentui-react-native/experimental-activity-indicator": {
      "name": "@fluentui-react-native/experimental-activity-indicator",
      "version": "0.9.7"
    },
    "@fluentui-react-native/experimental-appearance-additions": {
      "name": "@fluentui-react-native/experimental-appearance-additions",
      "version": "0.6.7"
    },
    "@fluentui-react-native/experimental-avatar": {
      "name": "@fluentui-react-native/experimental-avatar",
      "version": "0.20.7"
    },
    "@fluentui-react-native/experimental-checkbox": {
      "name": "@fluentui-react-native/experimental-checkbox",
      "version": "0.16.7"
    },
    "@fluentui-react-native/drawer": {
      "name": "@fluentui-react-native/drawer",
      "version": "0.3.7"
    },
    "@fluentui-react-native/dropdown": {
      "name": "@fluentui-react-native/dropdown",
      "version": "0.9.10"
    },
    "@fluentui-react-native/experimental-expander": {
      "name": "@fluentui-react-native/experimental-expander",
      "version": "0.7.7"
    },
    "@fluentui-react-native/experimental-link": {
      "name": "@fluentui-react-native/experimental-link",
      "version": "0.7.7"
    },
    "@fluentui-react-native/experimental-menu-button": {
      "name": "@fluentui-react-native/experimental-menu-button",
      "version": "0.9.11"
    },
    "@fluentui-react-native/experimental-native-date-picker": {
      "name": "@fluentui-react-native/experimental-native-date-picker",
      "version": "0.10.0"
    },
    "@fluentui-react-native/experimental-native-font-metrics": {
      "name": "@fluentui-react-native/experimental-native-font-metrics",
      "version": "0.5.0"
    },
    "@fluentui-react-native/popover": {
      "name": "@fluentui-react-native/popover",
      "version": "0.3.7"
    },
    "@fluentui-react-native/experimental-radio-group": {
      "name": "@fluentui-react-native/experimental-radio-group",
      "version": "0.12.9"
    },
    "@fluentui-react-native/experimental-shadow": {
      "name": "@fluentui-react-native/experimental-shadow",
      "version": "0.5.7"
    },
    "@fluentui-react-native/experimental-shimmer": {
      "name": "@fluentui-react-native/experimental-shimmer",
      "version": "0.12.9"
    },
    "@fluentui-react-native/spinner": {
      "name": "@fluentui-react-native/spinner",
      "version": "0.8.7"
    },
    "@fluentui-react-native/experimental-text": {
      "name": "@fluentui-react-native/experimental-text",
      "version": "0.14.7"
    },
    "@fluentui-react-native/tooltip": {
      "name": "@fluentui-react-native/tooltip",
      "version": "0.2.9"
    },
    "@fluentui-react-native/vibrancy-view": {
      "name": "@fluentui-react-native/vibrancy-view",
      "version": "0.1.0"
    },
    "@fluentui-react-native/component-cache": {
      "name": "@fluentui-react-native/component-cache",
      "version": "1.6.0"
    },
    "@fluentui-react-native/composition": {
      "name": "@fluentui-react-native/composition",
      "version": "0.10.0"
    },
    "@fluentui-react-native/eslint-config-rules": {
      "name": "@fluentui-react-native/eslint-config-rules",
      "version": "0.1.1"
    },
    "@fluentui-react-native/framework": {
      "name": "@fluentui-react-native/framework",
      "version": "0.13.6"
    },
    "@fluentui-react-native/immutable-merge": {
      "name": "@fluentui-react-native/immutable-merge",
      "version": "1.2.1"
    },
    "@fluentui-react-native/memo-cache": {
      "name": "@fluentui-react-native/memo-cache",
      "version": "1.3.1"
    },
    "@fluentui-react-native/merge-props": {
      "name": "@fluentui-react-native/merge-props",
      "version": "0.8.0"
    },
    "@fluentui-react-native/theme": {
      "name": "@fluentui-react-native/theme",
      "version": "0.10.6"
    },
    "@fluentui-react-native/themed-stylesheet": {
      "name": "@fluentui-react-native/themed-stylesheet",
      "version": "1.6.0"
    },
    "@fluentui-react-native/use-slot": {
      "name": "@fluentui-react-native/use-slot",
      "version": "0.5.0"
    },
    "@fluentui-react-native/use-slots": {
      "name": "@fluentui-react-native/use-slots",
      "version": "0.9.0"
    },
    "@fluentui-react-native/use-styling": {
      "name": "@fluentui-react-native/use-styling",
      "version": "0.12.0"
    },
    "@fluentui-react-native/use-tokens": {
      "name": "@fluentui-react-native/use-tokens",
      "version": "0.5.0"
    },
    "@fluentui/react-native": {
      "name": "@fluentui/react-native",
      "version": "0.40.1"
    },
    "@fluentui-react-native/android-theme": {
      "name": "@fluentui-react-native/android-theme",
      "version": "0.24.1"
    },
    "@fluentui-react-native/apple-theme": {
      "name": "@fluentui-react-native/apple-theme",
      "version": "0.27.1"
    },
    "@fluentui-react-native/default-theme": {
      "name": "@fluentui-react-native/default-theme",
      "version": "0.25.1"
    },
    "@fluentui-react-native/theme-tokens": {
      "name": "@fluentui-react-native/theme-tokens",
      "version": "0.26.5"
    },
    "@fluentui-react-native/theme-types": {
      "name": "@fluentui-react-native/theme-types",
      "version": "0.38.0"
    },
    "@fluentui-react-native/theming-utils": {
      "name": "@fluentui-react-native/theming-utils",
      "version": "0.25.5"
    },
    "@fluentui-react-native/win32-theme": {
      "name": "@fluentui-react-native/win32-theme",
      "version": "0.33.1"
    },
    "@fluentui-react-native/adapters": {
      "name": "@fluentui-react-native/adapters",
      "version": "0.12.0"
    },
    "@fluentui-react-native/interactive-hooks": {
      "name": "@fluentui-react-native/interactive-hooks",
      "version": "0.25.7"
    },
    "@fluentui-react-native/styling-utils": {
      "name": "@fluentui-react-native/styling-utils",
      "version": "0.6.0"
    },
    "@fluentui-react-native/tokens": {
      "name": "@fluentui-react-native/tokens",
      "version": "0.22.5"
    }
  },
  "0.71": {
    "@fluentui-react-native/e2e-testing": {
      "name": "@fluentui-react-native/e2e-testing",
      "version": "1.32.8"
    },
    "@fluentui-react-native/tester": {
      "name": "@fluentui-react-native/tester",
      "version": "0.157.10"
    },
    "@fluentui-react-native/tester-win32": {
      "name": "@fluentui-react-native/tester-win32",
      "version": "0.36.17"
    },
    "@fluentui-react-native/avatar": {
      "name": "@fluentui-react-native/avatar",
      "version": "1.10.18"
    },
    "@fluentui-react-native/badge": {
      "name": "@fluentui-react-native/badge",
      "version": "0.7.14"
    },
    "@fluentui-react-native/button": {
      "name": "@fluentui-react-native/button",
      "version": "0.35.11"
    },
    "@fluentui-react-native/callout": {
      "name": "@fluentui-react-native/callout",
      "version": "0.24.19"
    },
    "@fluentui-react-native/checkbox": {
      "name": "@fluentui-react-native/checkbox",
      "version": "0.21.7"
    },
    "@fluentui-react-native/chip": {
      "name": "@fluentui-react-native/chip",
      "version": "0.2.9"
    },
    "@fluentui-react-native/contextual-menu": {
      "name": "@fluentui-react-native/contextual-menu",
      "version": "0.22.25"
    },
    "@fluentui-react-native/divider": {
      "name": "@fluentui-react-native/divider",
      "version": "0.5.16"
    },
    "@fluentui-react-native/focus-trap-zone": {
      "name": "@fluentui-react-native/focus-trap-zone",
      "version": "0.10.14"
    },
    "@fluentui-react-native/focus-zone": {
      "name": "@fluentui-react-native/focus-zone",
      "version": "0.15.0"
    },
    "@fluentui-react-native/icon": {
      "name": "@fluentui-react-native/icon",
      "version": "0.19.16"
    },
    "@fluentui-react-native/input": {
      "name": "@fluentui-react-native/input",
      "version": "0.4.9"
    },
    "@fluentui-react-native/link": {
      "name": "@fluentui-react-native/link",
      "version": "0.20.7"
    },
    "@fluentui-react-native/menu": {
      "name": "@fluentui-react-native/menu",
      "version": "1.11.30"
    },
    "@fluentui-react-native/menu-button": {
      "name": "@fluentui-react-native/menu-button",
      "version": "0.11.31"
    },
    "@fluentui-react-native/notification": {
      "name": "@fluentui-react-native/notification",
      "version": "0.23.22"
    },
    "@fluentui-react-native/persona": {
      "name": "@fluentui-react-native/persona",
      "version": "0.14.12"
    },
    "@fluentui-react-native/persona-coin": {
      "name": "@fluentui-react-native/persona-coin",
      "version": "0.13.12"
    },
    "@fluentui-react-native/pressable": {
      "name": "@fluentui-react-native/pressable",
      "version": "0.10.13"
    },
    "@fluentui-react-native/radio-group": {
      "name": "@fluentui-react-native/radio-group",
      "version": "0.19.9"
    },
    "@fluentui-react-native/separator": {
      "name": "@fluentui-react-native/separator",
      "version": "0.16.10"
    },
    "@fluentui-react-native/stack": {
      "name": "@fluentui-react-native/stack",
      "version": "0.8.16"
    },
    "@fluentui-react-native/switch": {
      "name": "@fluentui-react-native/switch",
      "version": "0.11.7"
    },
    "@fluentui-react-native/text": {
      "name": "@fluentui-react-native/text",
      "version": "0.21.14"
    },
    "@uifabricshared/foundation-composable": {
      "name": "@uifabricshared/foundation-composable",
      "version": "0.12.2"
    },
    "@uifabricshared/foundation-compose": {
      "name": "@uifabricshared/foundation-compose",
      "version": "1.14.12"
    },
    "@uifabricshared/foundation-settings": {
      "name": "@uifabricshared/foundation-settings",
      "version": "0.13.2"
    },
    "@uifabricshared/foundation-tokens": {
      "name": "@uifabricshared/foundation-tokens",
      "version": "0.13.9"
    },
    "@uifabricshared/theme-registry": {
      "name": "@uifabricshared/theme-registry",
      "version": "0.10.1"
    },
    "@uifabricshared/themed-settings": {
      "name": "@uifabricshared/themed-settings",
      "version": "0.10.2"
    },
    "@uifabricshared/theming-ramp": {
      "name": "@uifabricshared/theming-ramp",
      "version": "0.19.4"
    },
    "@uifabricshared/theming-react-native": {
      "name": "@uifabricshared/theming-react-native",
      "version": "0.18.12"
    },
    "@fluentui-react-native/experimental-activity-indicator": {
      "name": "@fluentui-react-native/experimental-activity-indicator",
      "version": "0.8.12"
    },
    "@fluentui-react-native/experimental-appearance-additions": {
      "name": "@fluentui-react-native/experimental-appearance-additions",
      "version": "0.5.12"
    },
    "@fluentui-react-native/experimental-avatar": {
      "name": "@fluentui-react-native/experimental-avatar",
      "version": "0.19.11"
    },
    "@fluentui-react-native/experimental-button": {
      "name": "@fluentui-react-native/experimental-button",
      "version": "0.18.22"
    },
    "@fluentui-react-native/experimental-checkbox": {
      "name": "@fluentui-react-native/experimental-checkbox",
      "version": "0.15.17"
    },
    "@fluentui-react-native/drawer": {
      "name": "@fluentui-react-native/drawer",
      "version": "0.2.13"
    },
    "@fluentui-react-native/dropdown": {
      "name": "@fluentui-react-native/dropdown",
      "version": "0.8.29"
    },
    "@fluentui-react-native/experimental-expander": {
      "name": "@fluentui-react-native/experimental-expander",
      "version": "0.6.13"
    },
    "@fluentui-react-native/experimental-link": {
      "name": "@fluentui-react-native/experimental-link",
      "version": "0.6.16"
    },
    "@fluentui-react-native/experimental-menu-button": {
      "name": "@fluentui-react-native/experimental-menu-button",
      "version": "0.7.31"
    },
    "@fluentui-react-native/experimental-native-date-picker": {
      "name": "@fluentui-react-native/experimental-native-date-picker",
      "version": "0.9.1"
    },
    "@fluentui-react-native/experimental-native-font-metrics": {
      "name": "@fluentui-react-native/experimental-native-font-metrics",
      "version": "0.4.1"
    },
    "@fluentui-react-native/popover": {
      "name": "@fluentui-react-native/popover",
      "version": "0.2.11"
    },
    "@fluentui-react-native/experimental-radio-group": {
      "name": "@fluentui-react-native/experimental-radio-group",
      "version": "0.11.19"
    },
    "@fluentui-react-native/experimental-shadow": {
      "name": "@fluentui-react-native/experimental-shadow",
      "version": "0.4.12"
    },
    "@fluentui-react-native/experimental-shimmer": {
      "name": "@fluentui-react-native/experimental-shimmer",
      "version": "0.11.6"
    },
    "@fluentui-react-native/spinner": {
      "name": "@fluentui-react-native/spinner",
      "version": "0.7.15"
    },
    "@fluentui-react-native/tablist": {
      "name": "@fluentui-react-native/tablist",
      "version": "0.4.10"
    },
    "@fluentui-react-native/experimental-text": {
      "name": "@fluentui-react-native/experimental-text",
      "version": "0.13.14"
    },
    "@fluentui-react-native/vibrancy-view": {
      "name": "@fluentui-react-native/vibrancy-view",
      "version": "0.0.3"
    },
    "@fluentui-react-native/component-cache": {
      "name": "@fluentui-react-native/component-cache",
      "version": "1.5.1"
    },
    "@fluentui-react-native/composition": {
      "name": "@fluentui-react-native/composition",
      "version": "0.9.2"
    },
    "@fluentui-react-native/eslint-config-rules": {
      "name": "@fluentui-react-native/eslint-config-rules",
      "version": "0.1.1"
    },
    "@fluentui-react-native/framework": {
      "name": "@fluentui-react-native/framework",
      "version": "0.11.10"
    },
    "@fluentui-react-native/immutable-merge": {
      "name": "@fluentui-react-native/immutable-merge",
      "version": "1.2.1"
    },
    "@fluentui-react-native/memo-cache": {
      "name": "@fluentui-react-native/memo-cache",
      "version": "1.3.1"
    },
    "@fluentui-react-native/merge-props": {
      "name": "@fluentui-react-native/merge-props",
      "version": "0.7.1"
    },
    "@fluentui-react-native/theme": {
      "name": "@fluentui-react-native/theme",
      "version": "0.9.4"
    },
    "@fluentui-react-native/themed-stylesheet": {
      "name": "@fluentui-react-native/themed-stylesheet",
      "version": "1.5.2"
    },
    "@fluentui-react-native/use-slot": {
      "name": "@fluentui-react-native/use-slot",
      "version": "0.4.2"
    },
    "@fluentui-react-native/use-slots": {
      "name": "@fluentui-react-native/use-slots",
      "version": "0.8.2"
    },
    "@fluentui-react-native/use-styling": {
      "name": "@fluentui-react-native/use-styling",
      "version": "0.11.1"
    },
    "@fluentui-react-native/use-tokens": {
      "name": "@fluentui-react-native/use-tokens",
      "version": "0.4.2"
    },
    "@fluentui/react-native": {
      "name": "@fluentui/react-native",
      "version": "0.38.6"
    },
    "@fluentui-react-native/android-theme": {
      "name": "@fluentui-react-native/android-theme",
      "version": "0.18.9"
    },
    "@fluentui-react-native/apple-theme": {
      "name": "@fluentui-react-native/apple-theme",
      "version": "0.21.13"
    },
    "@fluentui-react-native/default-theme": {
      "name": "@fluentui-react-native/default-theme",
      "version": "0.19.11"
    },
    "@fluentui-react-native/theme-tokens": {
      "name": "@fluentui-react-native/theme-tokens",
      "version": "0.25.4"
    },
    "@fluentui-react-native/theme-types": {
      "name": "@fluentui-react-native/theme-types",
      "version": "0.32.3"
    },
    "@fluentui-react-native/theming-utils": {
      "name": "@fluentui-react-native/theming-utils",
      "version": "0.24.7"
    },
    "@fluentui-react-native/win32-theme": {
      "name": "@fluentui-react-native/win32-theme",
      "version": "0.27.10"
    },
    "@fluentui-react-native/adapters": {
      "name": "@fluentui-react-native/adapters",
      "version": "0.11.3"
    },
    "@fluentui-react-native/interactive-hooks": {
      "name": "@fluentui-react-native/interactive-hooks",
      "version": "0.24.12"
    },
    "@fluentui-react-native/styling-utils": {
      "name": "@fluentui-react-native/styling-utils",
      "version": "0.5.0"
    },
    "@fluentui-react-native/tokens": {
      "name": "@fluentui-react-native/tokens",
      "version": "0.21.6"
    }
  }
};
